### DISCUSSION TITLE
Consider Adding Management Modules for Panorama

### DISCUSSION THREAD

**Discussion by JulioPDX** [PaloAltoNetworks/pan-os-ansible#206] [Ideas]
Currently the collection does not allow some administrative tasks in Panorama like adding devices to device groups or template groups. This would be helpful when onboarding a device or removing a device from inventory.

It would be nice if there was a panorama module to add x serial number to device group/templatestack or add x serial number to log collector. 

Here is a concept layout for the module:

```yaml
- name: Add device to panorama with associated stuffs
  firewall_to_panorama:
    pan_url: some_url
    pan_auth: api_key
    state: present
    firewall_sn: some_sn
    device_group: some_device_group
    template_stack: some_template_stack
    collector: some_log_collector
    push_on_connect: True
```

Currently we are making API calls with ansible to get the template stack `/restapi/v10.0/Panorama/TemplateStacks?name=somegroup`, then parsing the output to either add a serial or remove a serial number from that location. Having a module doing this would remove some logic flows on the end user. Currently parsing the output and running through jinja to rebuild the JSON for the PUT is okay but probably not efficient. 

Thank you for the time and considering this.
