### DISCUSSION TITLE
Panos_admpwd Hangs

### DISCUSSION THREAD

**Discussion by DapperDeer** [PaloAltoNetworks/pan-os-ansible#272] [Q&A] [answered]
Hi there, I have a super basic Ansible script that is meant to just change the admin password using SSH. It should be mentioned that this is for a GCP VM-Series firewall.

```yml
---
- name: change admin password for newly deployed Palo Alto firewall
  hosts: firewall
  collections:
    - paloaltonetworks.panos
  gather_facts: no
  
  tasks:
    - name: Change admin password using SSH
      panos_admpwd:
        ip_address: '{{ provider.ip_address }}'
        newpassword: '{{ provider.new_password }}'
        key_filename: '{{ ansible_ssh_private_key_file }}'
      register: result
      until: not result|failed
      retries: 10
      delay: 30

    - name: panos commit
      panos_commit_firewall:
        provider: '{{ provider }}'
```

and my inventory.yml:

```yml
all:
  hosts:
  children:
    firewall:
      hosts:
        morannon: 
          ansible_host: xx.xxx.xx.xxx
          ansible_user: admin
          ansible_ssh_private_key_file: ssh.key
          provider:
            ip_address: xx.xxx.xx.xxx
            new_password: new_password
```
and for whatever reason, the task just hangs when establishing the connection.

 ```
TASK [Change admin password using SSH] **************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/dapper/Morannon/Ansible/morannon.yml:9
<xx.xxx.xx.xxx> ESTABLISH SSH CONNECTION FOR USER: admin
<xx.xxx.xx.xxx> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="ssh.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/dapper/.ansible/cp/52255bf5c1 xxx.xxx.xx.xxx '/bin/sh -c '"'"'echo ~admin && sleep 0'"'"''
```

I did find [this fixed issue](https://github.com/PaloAltoNetworks/pan-os-ansible/pull/21) that is exactly my problem, but it was fixed and leaving the connection ongoing never actually errors out or ends.

Here's my `ansible --version` output:

```
ansible [core 2.11.5] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dapper/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dapper/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/dapper/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dapper/.local/bin/ansible
  python version = 3.8.0 (default, Feb 25 2021, 22:10:10) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
```

I realize this may not be "the place" to ask this, but the LIVEcommunity doesn't seem as active as I need it to be, so I figured this is the second best place I could find.

**Comment by mrichardson03** [comment, marked as answer]
You need to be using `connection: local` so that the module executes on your system locally, instead of doing the typical Ansible method of copying and executing Python code over SSH. Here's an example that I just tried:

```
- hosts: firewall
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Change admin password using SSH
      panos_admpwd:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        newpassword: '{{ password }}'
        key_filename: '/tmp/ssh.key'

```
