### ISSUE TITLE
panos_l2_subinterface: fails on aggregate interfaces

### ISSUE THREAD

**Issue by slrz** [PaloAltoNetworks/pan-os-ansible#11]
## Describe the bug
The module fails when used with aggregate interfaces.

```yaml
panos_l2_subinterface:
  provider: "{{ provider }}"
  name: ae1.42
  tag: 42
  vlan_name: some_vlan
  zone_name: twilight_zone
```

## Expected behavior

Creation of subinterface `ae1.42` on aggregate interface `ae1`.

## Current behavior

Execution fails witth the following message:
> Failed refresh: Object doesn't exist: /config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet/entry[@name='ae1']

## Possible solution

When the named interface doesn't exist within the ethernet section of the config tree, try looking it up as an aggregate.

## Context

Evaluating how to deploy a pair of PA-5200s, each dual-connected to the switches (thus the need for link aggregation).
