### ISSUE TITLE
panos_admpwd hangs when connecting to AWS Palo Alto Firewall

### ISSUE THREAD

**Issue by michaelford85** [PaloAltoNetworks/pan-os-ansible#12]
## Describe the bug

panos_admpwd hangs when trying to establish a connection with a newly provisioned AWS-based Palo Alto Firewall. SSHing into the firewall from the terminal command line (with the appropriate SSH private key of course) works.

## Expected behavior

The panos_admpwd module should be applying a password to the specified user in order to allow for the other modules to be used, as they require a username and password rather than an SSH private key file.

## Current behavior

That playbook never gets past establishing a connection with the newly created firewall.

Playbook in question:
```
---
- name: Provision AWS Resources
  hosts: panos
  gather_facts: no
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/pan_credentials.yml

  tasks:

    - name: Configure admin password
      paloaltonetworks.panos.panos_admpwd:
        ip_address: "{{ inventory_hostname }}"
        username: "admin"
        key_filename: "{{ working_dir }}/{{ ec2_prefix }}-key-private.pem"
        newpassword: "{{ PAN_PASSWORD }}"
      register: result
      until: not result|failed
      retries: 10
      delay: 30
```

Results of the playbook:
```
TASK [Configure admin password] ***************************************************************************************************************************************************************
task path: /Users/michaelford/My Local Documents/github-workspace/ansible-panos/secure_firewalls.yml:20
Read vars_file './vars/default_vars.yml'
Read vars_file './credentials/pan_credentials.yml'
Read vars_file './vars/default_vars.yml'
Read vars_file './credentials/pan_credentials.yml'
<18.214.16.238> ESTABLISH SSH CONNECTION FOR USER: admin
<18.214.16.238> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/tmp/mford-panos-demo-key-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/Users/michaelford/.ansible/cp/ecf716a88b 18.214.16.238 '/bin/sh -c '"'"'echo ~admin && sleep 0'"'"''
```

Result of logging into the firewall on the terminal:
```
$ ssh admin@18.214.16.238 -i /tmp/mford-panos-demo-key-private.pem 
Last login: Sun Mar  8 14:13:41 2020 from 45.56.142.132
Welcome admin.
admin@PA-VM> 
```

## Context

Not having this module work properly, will force operators to manually change add passwords to firewalls, raising the barrier of entry to using ansible automation for Palo Alto firewalls.
## Your Environment

- Ansible Version used: 2.9.5
- Environment name and version: python 3.7.3
- Operating System and version: Mac OS Catalina
- Link to your project: https://github.com/michaelford85/ansible-panos/tree/tower-3.6
