### ISSUE TITLE
Removal of address groups doesn't work if only name is specified

### ISSUE THREAD

**Issue by joaopsys** [PaloAltoNetworks/pan-os-ansible#156]
## Describe the bug

Considering the following task:

```
- name: Delete address groups
  paloaltonetworks.panos.panos_address_group:
    provider: "{{ panorama }}"
    device_group: "{{ some_dg }}"
    name: test_delete
    state: absent
```

The playbook will throw back an error saying:

`failed: [xxx] => {"msg": "one of the following is required: static_value, dynamic_value"}`

## Expected behavior

The object should be deleted, without the need to specify static_value or dynamic_value. The 'name' should be enough

## Your Environment

- Collection: 2.1.0
- Python: 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
- Ansible: 2.9.14
- PAN-OS Python Library & version: pandevice 0.14.0, pan-os-python 1.0.2

**Comment by mrichardson03** [comment]
Can't replicate in `develop` with the integration test playbook that tests this specific case:

https://github.com/PaloAltoNetworks/pan-os-ansible/blob/develop/tests/integration/firewall/test_panos_address_group.yml

```
- name: test_panos_address_group - Delete
  panos_address_group:
    provider: '{{ device }}'
    name: 'Test'
    state: 'absent'
    device_group: '{{ device_group | default(omit) }}'
  register: result
```

Can you upgrade to the latest version of the collection and try again?
