### ISSUE TITLE
failed to apply bgp configuration when already exists

### ISSUE THREAD

**Issue by kevinhuy** [PaloAltoNetworks/pan-os-ansible#177]
## Describe the bug

When bgp configuration already exists, it failed with error below when trying to re-apply bgp config in panorama (9.0.10) with template.

the error concern bgp policy  import and export .

notice, that from scratch all the bgp config is sucessfuly apply.

Failed apply:  bgp -> policy -> import -> rules -> import-xxxx -> used-by 'xxx' is not a valid reference\n bgp -> policy -> import -> rules -> import-xxxx -> used-by is invalid"

bgp -> peer-group -> peer-grp-x -> peer -> peer-bgp-x -> connection-options -> authentication 'bgp-x' is not a valid reference\n bgp -> peer-group -> peer-grp-x -> peer -> peer-bgp-x -> connection-options -> authentication is invalid

## Expected behavior

it should re-apply without error, because the config alreay exists.

## Current behavior

failed on apply bgp config.

## Steps to reproduce

1. create initial config with this code below

- name: Configure BGP
      panos_bgp:
        provider: '{{ provider }}'
        enable: "{{ item.enable }}"
        router_id: "{{ item.router_id }}"
        local_as: "{{ item.local_as }}"
        allow_redist_default_route: "{{ item.allow_redist_default_route | default(omit) }}"
        ecmp_multi_as: "{{  item.ecmp_multi_as | default(omit) }}"
        enforce_first_as: "{{  item.enforce_first_as | default(omit) }}"
        global_bfd_profile: "{{  item.global_bfd_profile | default(omit) }}"
        install_route: "{{  item.install_route | default(omit) }}"
        reject_default_route: "{{  item.reject_default_route | default(omit) }}"
        vr_name: "{{ item.vr_name }}"
        template: "{{ tpl }}"
        commit: false

    - name: Create BGP Authentication Profile
      panos_bgp_auth:
        provider: '{{ provider }}'
        vr_name: "{{ item.vr_name }}"
        name: "{{ item.name }}"
        secret: "{{ item.secret }}"
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ bgp_auth }}"

    - name: Create BGP Peer Groups
      panos_bgp_peer_group:
        provider: '{{ provider }}'
        name: "{{ item.name }}"
        enable: "{{ item.enable }}"
        aggregated_confed_as_path: "{{ item.aggregated_confed_as_path }}"
        export_nexthop: "{{ item.export_nexthop }}"
        import_nexthop: "{{ item.import_nexthop }}"
        type: "{{ item.type }}"
        soft_reset_with_stored_info: "{{ item.soft_reset_with_stored_info }}"
        vr_name: "{{ item.vr_name }}"
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ bgp_peer_group }}"

    - name: Create BGP Peers
      panos_bgp_peer:
        provider: '{{ provider }}'
        name: "{{ item.name }}"
        enable: "{{ item.enable }}"
        connection_authentication: "{{ item.connection_authentication  | default(omit) }}"
        local_interface: "{{ item.local_interface }}"
        local_interface_ip: "{{ item.local_interface_ip }}"
        max_prefixes: "{{ item.max_prefixes | default(omit) }}"
        peer_address_ip: "{{ item.peer_address_ip }}"
        peer_as: "{{ item.peer_as }}"
        peer_group: "{{ item.peer_group }}"
        vr_name: "{{ item.vr_name }}"
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ bgp_peer }}"

    - name: Create Policy Import Rule
      panos_bgp_policy_rule:
          provider: '{{ provider }}'
          name: "{{ item.name }}"
          type: import
          vr_name: "{{ item.vr_name }}"
          action: "{{ item.action }}"
          address_prefix: "{{ item.address_prefix | default(omit) }}"
          action_as_path_prepend_times: "{{ item.action_as_path_prepend_times | default(omit)  }}"
          action_as_path_limit: "{{ item.action_as_path_limit | default(omit) }}"
          action_as_path_type: "{{ item.action_as_path_type | default(omit) }}"
          action_local_preference: "{{ item.action_local_preference  | default(omit) }}"
          action_med: "{{ item.action_med  | default(omit) }}"
          action_origin: "{{ item.action_origin  | default(omit) }}"
          enable: "{{ item.enable }}"
          match_afi: "{{ item.match_afi | default(omit)  }}"
          match_as_path_regex: "{{ item.match_community_regex  | default(omit) }}"
          match_community_regex: "{{ item.match_community_regex | default(omit) }}"
          match_extended_community_regex: "{{ item.match_extended_community_regex | default(omit) }}"
          match_from_peer: "{{ item.match_from_peer | default(omit) }}"
          match_med: "{{ item.match_med | default(omit) }}"
          match_nexthop: "{{ item.match_nexthop | default(omit) }}"
          match_route_table: "{{ item.match_route_table }}"
          match_safi: "{{ item.match_safi | default(omit) }}"
          used_by: "{{ item.used_by | default(omit) }}"
          template: "{{ tpl }}"
          commit: false
      with_items: "{{ bgp_policy_rule_import }}"
 

    - name: Create Policy Export Rule
      panos_bgp_policy_rule:
          provider: '{{ provider }}'
          name: "{{ item.name }}"
          type: export
          vr_name: "{{ item.vr_name }}"
          action: "{{ item.action }}"
          address_prefix: "{{ item.address_prefix | default(omit) }}"
          action_as_path_prepend_times: "{{ item.action_as_path_prepend_times | default(omit)  }}"
          action_as_path_limit: "{{ item.action_as_path_limit | default(omit) }}"
          action_as_path_type: "{{ item.action_as_path_type | default(omit) }}"
          action_local_preference: "{{ item.action_local_preference  | default(omit) }}"
          action_med: "{{ item.action_med  | default(omit) }}"
          action_origin: "{{ item.action_origin  | default(omit) }}"
          enable: "{{ item.enable }}"
          match_afi: "{{ item.match_afi | default(omit)  }}"
          match_as_path_regex: "{{ item.match_community_regex  | default(omit) }}"
          match_community_regex: "{{ item.match_community_regex | default(omit) }}"
          match_extended_community_regex: "{{ item.match_extended_community_regex | default(omit) }}"
          match_from_peer: "{{ item.match_from_peer | default(omit) }}"
          match_med: "{{ item.match_med | default(omit) }}"
          match_nexthop: "{{ item.match_nexthop | default(omit) }}"
          match_route_table: "{{ item.match_route_table }}"
          match_safi: "{{ item.match_safi | default(omit) }}"
          used_by: "{{ item.used_by | default(omit) }}"
          template: "{{ tpl }}"
          commit: false
      with_items: "{{ bgp_policy_rule_export }}"

    - name: Create BGP redistribute rule
      panos_bgp_redistribute:
          provider: '{{ provider }}'
          name: "{{ item.name }}"
          vr_name: "{{ item.vr_name }}"
          enable: "{{ item.enable }}"
          address_family_identifier: "{{ item.address_family_identifier }}"
          set_origin: "{{ item.set_origin  | default(omit) }}"
          set_as_path_limit: "{{ item.set_as_path_limit  | default(omit) }}"
          set_local_preference: "{{ item.set_local_preference  | default(omit) }}"
          set_med: "{{ item.set_med  | default(omit) }}"
          template: "{{ tpl }}"
          commit: false
      with_items: "{{ bgp_rdstb }}"
 
2. re-apply the playbook several times

## Your Environment

- Collection: 2.4.0
- Python: 3.8
- Ansible: 2.9.10
- PAN-OS Python Library & version (pan-os-python 1.0.2): 1.0.2

**Comment by mrichardson03** [comment]
While I can appreciate not wanting to share configs, you'll need to provide more than just blank variables so the issue can be replicated.

**Comment by kevinhuy** [comment]
hello 

is there a way to share it in private ?

**Comment by kevinhuy** [comment]
hello @mrichardson03 

please find below atttach the file with playbook and data in yml format. you should be able to reproduce the problem.

[bgp_issues.zip](https://github.com/PaloAltoNetworks/pan-os-ansible/files/5860941/bgp_issues.zip)

i m using panoarma 9.0.10

**Comment by mrichardson03** [comment]
Please add a playbook snippet (with variables filled in) directly to the issue.  I'm not going to open a ZIP attachment.

**Comment by kevinhuy** [comment]
Hello

Please find it below .

Thanks

````yaml
bgp:
- allow_redist_default_route: false
  enable: true
  install_route: false
  local_as: '64524'
  reject_default_route: true
  router_id: 10.211.100.14
  vr_name: default-VR
- enable: true
  install_route: true
  local_as: '64521'
  router_id: 10.172.0.1
  vr_name: VR2

bgp_auth:
- name: bgp-key-pub
  secret: -AQ==/AAAAAAaaAAAAAABBBBBBBBBBBBBBBBBBBB=
  vr_name: default-VR
- name: bgp-key-key1
  secret: -AQ==/AAAAAAaaAAAAAABBBBBBBBBBBBBBBBBBBB=
  vr_name: VR2
- name: bgp-key-key2
  secret: -AQ==/AAAAAAaaAAAAAABBBBBBBBBBBBBBBBBBBB=
  vr_name: VR2

bgp_peer_group:
- aggregated_confed_as_path: 'True'
  enable: 'True'
  export_nexthop: resolve
  import_nexthop: original
  name: aws-public-vif-peer
  soft_reset_with_stored_info: 'False'
  type: ebgp
  vr_name: default-VR
- aggregated_confed_as_path: 'True'
  enable: 'True'
  export_nexthop: use-self
  import_nexthop: original
  name: peer-grp-test-tunnel1
  soft_reset_with_stored_info: 'False'
  type: ebgp
  vr_name: VR2
- aggregated_confed_as_path: 'True'
  enable: 'True'
  export_nexthop: use-self
  import_nexthop: original
  name: peer-grp-test-tunnel2
  soft_reset_with_stored_info: 'False'
  type: ebgp
  vr_name: VR2
- aggregated_confed_as_path: 'True'
  enable: 'True'
  export_nexthop: resolve
  import_nexthop: original
  name: peer-core-test-tunnel-1
  soft_reset_with_stored_info: 'False'
  type: ebgp
  vr_name: VR2
- aggregated_confed_as_path: 'True'
  enable: 'True'
  export_nexthop: resolve
  import_nexthop: original
  name: peer-core-test-tunnel-2
  soft_reset_with_stored_info: 'False'
  type: ebgp
  vr_name: VR2

bgp_peer:
- connection_authentication: bgp-key-pub
  enable: 'True'
  local_interface: ae1.2110
  local_interface_ip: 70.211.68.237/30
  max_prefixes: '5000'
  name: aws-public-vif
  peer_address_ip: 70.211.68.238
  peer_as: '7224'
  peer_group: aws-public-vif-peer
  vr_name: default-VR
- connection_authentication: bgp-key-key1
  enable: 'True'
  local_interface: loopback.101
  local_interface_ip: 10.172.0.1/32
  max_prefixes: '5000'
  name: peer-bgp-us3-fw01
  peer_address_ip: 10.172.20.7
  peer_as: '65200'
  peer_group: peer-grp-test-tunnel1
  vr_name: VR2
- connection_authentication: bgp-key-key2
  enable: 'True'
  local_interface: loopback.101
  local_interface_ip: 10.172.0.1/32
  max_prefixes: '5000'
  name: peer-bgp-us3-fw02
  peer_address_ip: 10.172.20.8
  peer_as: '65210'
  peer_group: peer-grp-test-tunnel2
  vr_name: VR2
- enable: 'True'
  local_interface: tunnel.200
  local_interface_ip: 169.254.223.66/30
  max_prefixes: '5000'
  name: core-tgw-tunnel-1
  peer_address_ip: 169.254.223.65
  peer_as: '65229'
  peer_group: peer-core-test-tunnel-1
  vr_name: VR2
- enable: 'True'
  local_interface: tunnel.201
  local_interface_ip: 169.254.32.134/30
  max_prefixes: '5000'
  name: core-tgw-tunnel-2
  peer_address_ip: 169.254.32.133
  peer_as: '65229'
  peer_group: peer-core-test-tunnel-2
  vr_name: VR2

bgp_policy_rule_export:
- action: allow
  action_as_path_type: none
  action_origin: incomplete
  address_prefix:
  - exact: 'True'
    name: 70.211.68.236/30
  enable: true
  match_route_table: unicast
  name: export-aws-public-vif
  used_by:
  - aws-public-vif-peer
  vr_name: default-VR
- action: allow
  action_as_path_prepend_times: 10
  action_as_path_type: prepend
  action_origin: incomplete
  address_prefix:
  - exact: 'True'
    name: 172.20.0.0/19
  enable: true
  match_route_table: unicast
  name: export-allow-vpc-to-test-tunnel1
  used_by:
  - peer-grp-test-tunnel1
  vr_name: VR2
- action: allow
  action_as_path_prepend_times: 15
  action_as_path_type: prepend
  action_origin: incomplete
  address_prefix:
  - exact: 'True'
    name: 172.20.0.0/19
  enable: true
  match_route_table: unicast
  name: export-allow-vpc-to-test-tunnel2
  used_by:
  - peer-grp-test-tunnel2
  vr_name: VR2
- action: allow
  action_as_path_type: none
  action_origin: incomplete
  address_prefix:
  - exact: 'True'
    name: 10.211.0.0/16
  enable: true
  match_route_table: unicast
  name: allow-to-core-tgw-tunnel-1
  used_by:
  - peer-core-test-tunnel-1
  vr_name: VR2
- action: allow
  action_as_path_prepend_times: 2
  action_as_path_type: prepend
  action_origin: incomplete
  address_prefix:
  - exact: 'True'
    name: 10.211.0.0/16
  enable: true
  match_route_table: unicast
  name: allow-to-core-tgw-tunnel-2
  used_by:
  - peer-core-test-tunnel-2
  vr_name: VR2

bgp_policy_rule_import:
- action: allow
  action_as_path_type: none
  action_origin: incomplete
  address_prefix: []
  enable: true
  match_community_regex: 7224:8100
  match_route_table: unicast
  name: import-aws-public-vif
  used_by:
  - aws-public-vif-peer
  vr_name: default-VR
- action: allow
  action_as_path_type: none
  action_med: 95
  action_origin: incomplete
  address_prefix:
  - exact: 'True'
    name: 10.250.210.0/23
  enable: true
  match_route_table: unicast
  name: allow-from-core-tgw-tunnel-1
  used_by:
  - peer-core-test-tunnel-1
  vr_name: VR2
- action: allow
  action_as_path_type: none
  action_med: 250
  action_origin: incomplete
  address_prefix:
  - exact: 'True'
    name: 10.250.210.0/23
  enable: true
  match_route_table: unicast
  name: allow-from-core-tgw-tunnel-2
  used_by:
  - peer-core-test-tunnel-2
  vr_name: VR2

aggregate_interfaces:
- lacp_enable: true
  lacp_mode: active
  lacp_passive_pre_negotiation: ''
  lacp_rate: fast
  mode: layer3
  name: ae1
  vr_name: default-VR

interfaces:
- aggregate_name: ae8
  if_name: ethernet1/11
  mode: aggregate-group
- aggregate_name: ae8
  if_name: ethernet1/12
  mode: aggregate-group

loopback_interface:
- if_name: loopback.101
  ip:
  - 10.172.0.1/32
  vr_name: VR2
  zone_name: zone-loop

sub_interfaces:
- ip:
  - 70.211.68.237/30
  ipv6_enabled: None
  name: ae1.2110
  tag: 2110
  vr_name: default-VR
  zone_name: zone-use1

tunnel:
- if_name: tunnel.200
  ip:
  - 169.254.223.66/30
  vr_name: VR2
  zone_name: zone-test
- if_name: tunnel.201
  ip:
  - 169.254.32.134/30
  vr_name: VR2
  zone_name: zone-test

````

Playbook here
````yaml

---
- hosts: localhost
  connection: local
  gather_facts: False

  collections:
      - paloaltonetworks.panos
  
  vars:
    tpl: 'tmpl-test'

  tasks:

    - name: create template
      panos_type_cmd:
        provider: '{{ provider }}'
        cmd: "set"
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']/template
        element: |
          <entry name="{{ item }}"/>
      with_items: "{{ tpl }}"

    - name: Create Aggregated Interfaces
      panos_aggregate_interface:
        provider: '{{ provider }}'
        mode: '{{ item.mode }}'
        if_name: '{{ item.name }}'
        zone_name: '{{ item.zone | default(omit) }}'
        vr_name: '{{ item.vr_name | default(omit) }}'
        commit: false
        template: "{{ tpl }}"
      with_items: '{{ aggregate_interfaces }}'

    - name: Create Interfaces Tunnels
      panos_tunnel:
        provider: '{{ provider }}'
        if_name: '{{ item.if_name }}'
        ip: '{{ item.ip | default(omit) }}'
        comment: '{{ item.comment | default(omit) }}'
        vr_name: '{{ item.vr_name }}'
        zone_name: '{{ item.zone_name }}'
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ tunnel }}"

    - name: Create Interfaces Loopbacks
      panos_loopback_interface:
        provider: '{{ provider }}'
        if_name: '{{ item.if_name }}'
        ip: '{{ item.ip  | default(omit) }}'
        comment: '{{ item.comment | default(omit) }}'
        vr_name: '{{ item.vr_name | default(none) }}'
        zone_name: '{{ item.zone_name | default(omit) }}'
        management_profile: '{{ item.management_profile | default(omit) }}'
        mode: '{{ item.mode | default(omit) }}'
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ loopback_interface }}"

    - name: Create Sub-Interfaces
      panos_l3_subinterface:
        provider: '{{ provider }}'
        enable_dhcp: false
        name: '{{ item.name }}'
        ip: '{{ item.ip  | default(omit) }}'
        comment: '{{ item.comment | default(omit) }}'
        vr_name: '{{ item.vr_name }}'
        zone_name: '{{ item.zone_name | default(none) }}'
        vsys: vsys1
        tag: '{{ item.tag }}'
        template: "{{ tpl }}"
      with_items: "{{ sub_interfaces }}"
 
    - name: Configure BGP
      panos_bgp:
        provider: '{{ provider }}'
        enable: "{{ item.enable }}"
        router_id: "{{ item.router_id }}"
        local_as: "{{ item.local_as }}"
        allow_redist_default_route: "{{ item.allow_redist_default_route | default(omit) }}"
        ecmp_multi_as: "{{  item.ecmp_multi_as | default(omit) }}"
        enforce_first_as: "{{  item.enforce_first_as | default(omit) }}"
        global_bfd_profile: "{{  item.global_bfd_profile | default(omit) }}"
        install_route: "{{  item.install_route | default(omit) }}"
        reject_default_route: "{{  item.reject_default_route | default(omit) }}"
        vr_name: "{{ item.vr_name }}"
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ bgp }}"

    - name: Create BGP Authentication Profile
      panos_bgp_auth:
        provider: '{{ provider }}'
        vr_name: "{{ item.vr_name }}"
        name: "{{ item.name }}"
        secret: "{{ item.secret }}"
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ bgp_auth }}"

    - name: Create BGP Peer Groups
      panos_bgp_peer_group:
        provider: '{{ provider }}'
        name: "{{ item.name }}"
        enable: "{{ item.enable }}"
        aggregated_confed_as_path: "{{ item.aggregated_confed_as_path }}"
        export_nexthop: "{{ item.export_nexthop }}"
        import_nexthop: "{{ item.import_nexthop }}"
        type: "{{ item.type }}"
        soft_reset_with_stored_info: "{{ item.soft_reset_with_stored_info }}"
        vr_name: "{{ item.vr_name }}"
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ bgp_peer_group }}"

    - name: Create BGP Peers
      panos_bgp_peer:
        provider: '{{ provider }}'
        name: "{{ item.name }}"
        enable: "{{ item.enable }}"
        connection_authentication: "{{ item.connection_authentication  | default(omit) }}"
        local_interface: "{{ item.local_interface }}"
        local_interface_ip: "{{ item.local_interface_ip }}"
        max_prefixes: "{{ item.max_prefixes | default(omit) }}"
        peer_address_ip: "{{ item.peer_address_ip }}"
        peer_as: "{{ item.peer_as }}"
        peer_group: "{{ item.peer_group }}"
        vr_name: "{{ item.vr_name }}"
        template: "{{ tpl }}"
        commit: false
      with_items: "{{ bgp_peer }}"

    - name: Create Policy Import Rule
      panos_bgp_policy_rule:
          provider: '{{ provider }}'
          name: "{{ item.name }}"
          type: import
          vr_name: "{{ item.vr_name }}"
          action: "{{ item.action }}"
          address_prefix: "{{ item.address_prefix | default(omit) }}"
          action_as_path_prepend_times: "{{ item.action_as_path_prepend_times | default(omit)  }}"
          action_as_path_limit: "{{ item.action_as_path_limit | default(omit) }}"
          action_as_path_type: "{{ item.action_as_path_type | default(omit) }}"
          action_local_preference: "{{ item.action_local_preference  | default(omit) }}"
          action_med: "{{ item.action_med  | default(omit) }}"
          action_origin: "{{ item.action_origin  | default(omit) }}"
          enable: "{{ item.enable }}"
          match_afi: "{{ item.match_afi | default(omit)  }}"
          match_as_path_regex: "{{ item.match_as_path_regex  | default(omit) }}"
          match_community_regex: "{{ item.match_community_regex | default(omit) }}"
          match_extended_community_regex: "{{ item.match_extended_community_regex | default(omit) }}"
          match_from_peer: "{{ item.match_from_peer | default(omit) }}"
          match_med: "{{ item.match_med | default(omit) }}"
          match_nexthop: "{{ item.match_nexthop | default(omit) }}"
          match_route_table: "{{ item.match_route_table }}"
          match_safi: "{{ item.match_safi | default(omit) }}"
          used_by: "{{ item.used_by | default(omit) }}"
          template: "{{ tpl }}"
          commit: false
      with_items: "{{ bgp_policy_rule_import }}"

    - name: Create Policy Export Rule
      panos_bgp_policy_rule:
          provider: '{{ provider }}'
          name: "{{ item.name }}"
          type: export
          vr_name: "{{ item.vr_name }}"
          action: "{{ item.action }}"
          address_prefix: "{{ item.address_prefix | default(omit) }}"
          action_as_path_prepend_times: "{{ item.action_as_path_prepend_times | default(omit)  }}"
          action_as_path_limit: "{{ item.action_as_path_limit | default(omit) }}"
          action_as_path_type: "{{ item.action_as_path_type | default(omit) }}"
          action_local_preference: "{{ item.action_local_preference  | default(omit) }}"
          action_med: "{{ item.action_med  | default(omit) }}"
          action_origin: "{{ item.action_origin  | default(omit) }}"
          enable: "{{ item.enable }}"
          match_afi: "{{ item.match_afi | default(omit)  }}"
          match_as_path_regex: "{{ item.match_as_path_regex  | default(omit) }}"
          match_community_regex: "{{ item.match_community_regex | default(omit) }}"
          match_extended_community_regex: "{{ item.match_extended_community_regex | default(omit) }}"
          match_from_peer: "{{ item.match_from_peer | default(omit) }}"
          match_med: "{{ item.match_med | default(omit) }}"
          match_nexthop: "{{ item.match_nexthop | default(omit) }}"
          match_route_table: "{{ item.match_route_table }}"
          match_safi: "{{ item.match_safi | default(omit) }}"
          used_by: "{{ item.used_by | default(omit) }}"
          template: "{{ tpl }}"
          commit: false
      with_items: "{{ bgp_policy_rule_export }}"



````
