### ISSUE TITLE
panos_import: Failed to import config to Pan OS Device

### ISSUE THREAD

**Issue by Udayendu** [PaloAltoNetworks/pan-os-ansible#18]
## Describe the bug
Failed to import configuration to pan OS device

## Expected behavior
It should be able to import the config every time. Some time its working and some time failed to import the config.

## Current behavior
90% time unable to import 

~~~
TASK [Import configuration file into FW] ********************************************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'PanXapiError' object has no attribute 'message'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_panos_import_payload_75kydk6b/ansible_panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py\", line 180, in main\n  File \"/tmp/ansible_panos_import_payload_75kydk6b/ansible_panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py\", line 99, in import_file\n  File \"/usr/local/lib/python3.6/dist-packages/pan/xapi.py\", line 637, in keygen\n    raise PanXapiError(self.status_detail)\npan.xapi.PanXapiError: URLError: reason: [Errno 113] No route to host\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1585567740.856-61302474294564/AnsiballZ_panos_import.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1585567740.856-61302474294564/AnsiballZ_panos_import.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1585567740.856-61302474294564/AnsiballZ_panos_import.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_panos_import_payload_75kydk6b/ansible_panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py\", line 193, in <module>\n  File \"/tmp/ansible_panos_import_payload_75kydk6b/ansible_panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py\", line 183, in main\nAttributeError: 'PanXapiError' object has no attribute 'message'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
~~~

## Possible solution
Manual deployment is working but not through ansible.

## Steps to reproduce
1. Try to deploy 4 to 5 firewall through some script one by one. 
2. Some time it fail for all the OVA and some time  it will work for 1 or 2 ova.

## Your Environment
$ ansible --version
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]

Using paloalto collections.

**Comment by Udayendu** [comment]
## Playbook:
~~~
# cat 01_firewall-config.yml
---
- name: Firewall Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - 01_PrimaryDC_Mgmt_FWA.yml

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Import configuration file into FW
      panos_import:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        file: '{{ config_file }}'
        category: 'configuration'
      register: result

    - name: Load the configuration file to FW
      panos_loadcfg:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        file: '{{ result.filename }}'
        commit: True
~~~

**Comment by shinmog** [comment]
@Udayendu 

I've just pushed up an update to this module that should properly show the error message.  Can you please try an import with this tweak (it's on the `develop` branch) and report what the actual error is?

**Comment by Udayendu** [comment]
@shinmog ,

Indeed it was a timeout issue. I have added a wait time on my playbook before trying to load the config and thats working perfectly. Here is my playbook:

```
---
- name: Firewall Configuration '{{ vsphere_vm_name }}'
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - 01_PrimaryDC_Mgmt_FWA.yml

  collections:
    - paloaltonetworks.panos

  tasks:
    # Wait 1 minutes, then check every 5 seconds for 5 minutes.
    - name: wait for reboot
      panos_check:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        initial_delay: 60
        interval: 5
        timeout: 300

    - name: Import configuration file into FW
      panos_import:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        file: '{{ config_file }}'
        category: 'configuration'
      register: result

    - name: Load the configuration file to FW
      panos_loadcfg:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        file: '{{ result.filename }}'
        commit: True
```

But any way i will try your patch and then let you know. I need couple of days to test it out.
