### ISSUE TITLE
panos_lic raises exception on success

### ISSUE THREAD

**Issue by nembery** [PaloAltoNetworks/pan-os-ansible#183]
## Describe the bug

panos_lic module fails when the auth code is actually changed and the device is gets licensed

TASK [Activate my authcode] ****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: http.client.RemoteDisconnected: Remote end closed connection without response
fatal: [panos]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1612461327.0820713-95-266677746926753/AnsiballZ_panos_lic.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1612461327.0820713-95-266677746926753/AnsiballZ_panos_lic.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1612461327.0820713-95-266677746926753/AnsiballZ_panos_lic.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_lic', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_panos_lic_payload_0o_i8wzw/ansible_panos_lic_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_lic.py\", line 145, in <module>\n  File \"/tmp/ansible_panos_lic_payload_0o_i8wzw/ansible_panos_lic_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_lic.py\", line 123, in main\n  File \"/usr/local/lib/python3.7/site-packages/panos/base.py\", line 5058, in activate_feature_using_authorization_code\n    result = self.op('request license fetch auth-code \"{0}\"'.format(code))\n  File \"/usr/local/lib/python3.7/site-packages/panos/firewall.py\", line 208, in op\n    cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer\n  File \"/usr/local/lib/python3.7/site-packages/panos/base.py\", line 3775, in op\n    cmd, vsys, cmd_xml, extra_qs, retry_on_peer=retry_on_peer\n  File \"/usr/local/lib/python3.7/site-packages/panos/base.py\", line 3626, in method\n    super_method(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/pan/xapi.py\", line 951, in op\n    self.__type_op(cmd, vsys, extra_qs)\n  File \"/usr/local/lib/python3.7/site-packages/pan/xapi.py\", line 969, in __type_op\n    response = self.__api_request(query)\n  File \"/usr/local/lib/python3.7/site-packages/pan/xapi.py\", line 545, in __api_request\n    response = urlopen(**kwargs)\n  File \"/usr/local/lib/python3.7/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/local/lib/python3.7/urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n  File \"/usr/local/lib/python3.7/urllib/request.py\", line 543, in _open\n    '_open', req)\n  File \"/usr/local/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/usr/local/lib/python3.7/urllib/request.py\", line 1393, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/local/lib/python3.7/urllib/request.py\", line 1353, in do_open\n    r = h.getresponse()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1369, in getresponse\n    response.begin()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 310, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 279, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

## Expected behavior

Successfully licensing the NGFW causes several processes to restart, which in turn, causes the connection to get disconnected. This is expected and should be handled in the module itself

## Current behavior
Confuses users who things the operation actually failed

## Possible solution
Catch the RemoteDisconnected exception and report success back to the user. A failed license attempt will report back a sensible error message, so the exception is proof of success.

Notes should be added to the docs that the user should anticipate a loss of connectivity for some time until the processes restart

## Steps to reproduce

```yaml

    - block:
        - name: Activate my authcode
          # This firewall must be licensed to pull dynamic content and software updates
          panos_lic:
            provider: '{{ provider }}'
            auth_code: '{{ auth_code }}'
          register: activate_authcode

        - name: Pause for Service Restart
          pause:
            seconds: 180
          when: activate_authcode.changed
          notify: "reboot"

      rescue:
        - name: Pause for Service Restart (Rescue)
          pause:
            seconds: 180
          notify: "reboot"

```

Use this block to see the exception. Posting this here as a work around for other users who may encounter this error

## Your Environment

- Collection:
- Python:
- Ansible:
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):
