### ISSUE TITLE
panos_virtual_router not idempotent

### ISSUE THREAD

**Issue by dstogsdill** [PaloAltoNetworks/pan-os-ansible#191]
## Describe the bug
This bug is related to [issue #4](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/4).  I am currently developing a fix for this module.

The panos_virtual_router is not idempotent when child types are configured on the device.  Child types being those identified in the  pan-os-python package.

```
       "network.StaticRoute",
        "network.StaticRouteV6",
        "network.RedistributionProfile",
        "network.RedistributionProfileIPv6",
        "network.Ospf",
        "network.Bgp"
```

Additionally, if an interface is added to the virtual router outside of this module (i.e. assigning a virtual router to an interface using panos_l3_subinterface) this module will overwrite the existing configuration and removes the interface.  

## Expected behavior

1. This module should not register a change unless one of the module arguments is different than what is configured on the device.  

2. Since there are multiple ways to add an interface to a virtual router this module should not remove interfaces added outside of this module.  

## Current behavior

The module registers a change if a child object is configured.
The module registers a change if an interface is added outside of this module

## Possible solution

This module is relying on the pan object 'equal' function from the the base.py pan-os-python package.

            if not item.equal(virtual_router, compare_children=False):
                changed = True
                virtual_router.extend(item.children)

This looks to be doing a straight string comparison of the XML representation of the objects. unfortunately if there is a change to the device configuration outside of this module (say assigning a virtual router to an interface using panos_l3_subinterface) then this will ALWAYS incorrectly detect a change.

## Steps to reproduce

1. Run the playbook once to create the virtual router & L3 interface
2. Run the playbook a second time

On the second run both tasks should say ```ok```

#### Sample Playbook
```
---
- name: Palo Idempotent Testing
  hosts: lab
  gather_facts: no
  connection: local
  collections:
    - paloaltonetworks.panos

  vars:
    pan:
      ip_address: 'panorama.mydomain.com'
      username: 'admin'
      password: '******'

  tasks:
  - name: Configure Virtual Router
    panos_virtual_router:
      provider: '{{ pan }}'
      name: DEV-TEST
      vsys: TEST_vsys
      interface: ["ethernet1/3"]
      template: ANSIBLE-TEST
    delegate_to: localhost
    no_log: False

    - name: Configure L3 Subinterface
      panos_interface:
        provider: '{{ pan }}'
        if_name: ethernet1/4
        mode: layer3
        zone_name: TEST_Public
        ip: ["192.168.2.1/24"]
        enable_dhcp: false
        vr_name: DEV-TEST
        vsys: TEST_vsys
        template: ANSIBLE-TEST
      delegate_to: localhost
      no_log: False
```

## Screenshots

![Screen Shot 2021-02-13 at 12 04 43 PM](https://user-images.githubusercontent.com/1187042/107856087-df8d6c00-6df3-11eb-92bd-5ab364592f37.png)

## Context

I am attempting to use Ansible to configure the virtual router, interfaces and zones on Panorama templates.  Currently, each time I run the playbook it says there is a change.  Additionally, if i configure OSPF manually on the virtual router (since there is no Ansible module) the OSPF changes are removed entirely.  

## Your Environment

- Collection: paloaltonetworks.panos
- Python: 3.7
- Ansible: 2.10.7
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pandevice=0.14.0, pan-python=0.16.0, pan-os-python=1.0.2

**Comment by dstogsdill** [comment]
Still unsure why it's failing.  It has passed the ansible-sanity test

![Screen Shot 2021-02-15 at 10 57 49 AM](https://user-images.githubusercontent.com/1187042/107968740-bba96200-6f7c-11eb-8f65-683effb86470.png)

**Comment by btorresgil** [comment]
@dstogsdill I tried reproducing both issues and here's my analysis:

> Issue 1: This module should not register a change unless one of the module arguments is different than what is configured on the device.

I created a virtual router and added a static route to it. I've run this a dozen time with different changes and everything works as expected. When no change is made, I get an OK for both. So I'm not able to reproduce this issue. Do you have a sample playbook that shows this issue?

Here are the modules I used to test:
```yaml
    - name: Configure Virtual Router
      panos_virtual_router:
        provider: '{{ pan }}'
        name: default
        vsys: vsys1
        interface: ['ethernet1/3', 'ethernet1/4']
        template: 'my_template'
      delegate_to: localhost
      no_log: False

    - name: Configure Static Route
      panos_static_route:
        provider: '{{ pan }}'
        name: testroute
        destination: 10.0.0.0/24
        nexthop: 4.4.4.4
        template: 'my_template'
      delegate_to: localhost
      no_log: False
```

> 2. Since there are multiple ways to add an interface to a virtual router this module should not remove interfaces added outside of this module.

This is working as expected because each module is declarative, so the virtual router module expects to be given the end-state. So you have to pass both interface to the virtual router. The interfaces have to exist to provide them to the virtual router, so you have to switch the order in your example so the virtual router is last.

Here's a working example:
```yaml
tasks:
    - name: Configure first L3 Interface
      panos_interface:
        provider: '{{ pan }}'
        if_name: ethernet1/3
        mode: layer3
        ip: ['192.168.2.1/24']
        enable_dhcp: false
        vr_name: default
        vsys: vsys1
        template: 'my_template'
      delegate_to: localhost
      no_log: False

    - name: Configure second L3 Interface
      panos_interface:
        provider: '{{ pan }}'
        if_name: ethernet1/4
        mode: layer3
        ip: ['192.168.3.1/24']
        enable_dhcp: false
        vr_name: default
        vsys: vsys1
        template: 'my_template'
      delegate_to: localhost
      no_log: False

    - name: Configure Virtual Router
      panos_virtual_router:
        provider: '{{ pan }}'
        name: default
        vsys: vsys1
        interface: ['ethernet1/3', 'ethernet1/4']
        template: 'my_template'
      delegate_to: localhost
      no_log: False
```

When I run this playbook multiple times I get OK for all 3 modules.

This does raise the question if the interface modules should affect the virtual router. They probably shouldn't because it creates a redundant API call and affects configuration that is outside the interface. We are looking into changing this behavior, but that would be a breaking change. Open to your thoughts on this.
