### ISSUE TITLE
How to run raw configure commands?

### ISSUE THREAD

**Issue by chancez** [PaloAltoNetworks/pan-os-ansible#201]
I'm seeing gaps in support for configuring some things, and I'm wondering how I can run commands from within the `configure` mode. Eg:

```
configure
set shared log-settings config match-list config-any send-syslog "syslog-ng-production"
```

**Comment by chancez** [comment]
For anyone else trying to do something similar. I came up with the following approach:

I have a task which I iterate over to create 1 match list entry per iteration:
```
- name: Set system/correlation/config log match list (panos)
  vars:
    panos_match_lists:
      - name: system-infomational
         type: system
         filter: "(severity eq informational)"
         syslog_profiles: ["{{ panos_syslog_profile_name }}"]
         snmptrap_profile: librenms
  include_tasks: panos_match_list.yml
  loop: "{{ panos_match_lists }}"
  loop_control:
    loop_var: entry
  when: ansible_network_os == 'paloaltonetworks.panos.panos'
```

`panos_match_list.yml`:
```
# Expects an object 'entry' to be passed in with the following fields:
# name, filter, and type
# and at least one of: syslog_profile, snmptrap_profile, email_profile

- name: Remove existing log match list entry {{ entry.name }} (panos)
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ panos_provider }}'
    cmd: 'delete'
    xpath: "/config/shared/log-settings/{{ entry.type }}/match-list/entry[@name='{{ entry.name }}']"
  when: ansible_network_os == 'paloaltonetworks.panos.panos' and not (entry.retain_existing | default(false))

- name: Set log match list entry {{ entry.name }} filter (panos)
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ panos_provider }}'
    cmd: 'set'
    xpath: "/config/shared/log-settings/{{ entry.type }}/match-list/entry[@name='{{ entry.name }}']"
    element: "<filter>{{ entry.filter }}</filter>"
  when: ansible_network_os == 'paloaltonetworks.panos.panos'

- name: Set log match list entry {{ entry.name }} send-syslog (panos)
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ panos_provider }}'
    cmd: 'set'
    xpath: "/config/shared/log-settings/{{ entry.type }}/match-list/entry[@name='{{ entry.name }}']/send-syslog"
    element: "<member>{{ item }}</member>"
  loop: "{{ entry.syslog_profiles }}"
  when: ansible_network_os == 'paloaltonetworks.panos.panos' and entry.syslog_profiles is defined

- name: Set log match list entry {{ entry.name }} send-snmptrap (panos)
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ panos_provider }}'
    cmd: 'set'
    xpath: "/config/shared/log-settings/{{ entry.type }}/match-list/entry[@name='{{ entry.name }}']/send-snmptrap"
    element: "<member>{{ entry.snmptrap_profile }}</member>"
  when: ansible_network_os == 'paloaltonetworks.panos.panos' and entry.snmptrap_profile is defined

- name: Set log match list entry {{ entry.name }} send-email (panos)
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ panos_provider }}'
    cmd: 'set'
    xpath: "/config/shared/log-settings/{{ entry.type }}/match-list/entry[@name='{{ entry.name }}']/send-email"
    element: "<member>{{ entry.email_profile }}</member>"
  when: ansible_network_os == 'paloaltonetworks.panos.panos' and entry.email_profile is defined
```
