### ISSUE TITLE
zone assignation not working on panos_l3_subinterface

### ISSUE THREAD

**Issue by gdmndr** [PaloAltoNetworks/pan-os-ansible#238]
## Describe the bug

Problem when using paloaltonetworks.panos.panos_l3_subinterface module for assign a new created sub interface to a zone.

i use a panorama vm on PANOS 9.1.9 ( and a template configuration  ) for this action.

## Expected behavior

we just expecte that the interface was add to the right zone

## Current behavior

we've got a error "msg": "Failed setref:  layer3 'ethernet1/1.123' is not a valid reference

on the GUI, the interface is created but the interface can not be selected on the zone part and when i modify a parameters on the subinterface (the desc for exemple), the interface is selectable on the zone.
when I tri to add the interface to the zone with the module paloaltonetworks.panos.panos_zone i've got the same error.

this zone assignation work with interface and loopback module without trouble.

## Steps to reproduce

1. create a panorama VMon version 9.1.9  and a template named test_Template 
2. on this template create a l3 interface ethernet1/1
2. execute fllowing playbook with the provider varible like that
provider: 
    ip_address: "192.168.0.10"
    username: "{{ansible_user}}"
    password: "{{ansible_password}}"
```
---
- name: test csv file
  hosts: pan
  connection: local
  gather_facts: False
  tasks:
  - name: create subinterface for interconnexions
    paloaltonetworks.panos.panos_l3_subinterface :
      provider: '{{ provider }}'
      template: "test_Template"
      name: "ethernet1/1.123"
      enable_dhcp: yes
      tag: 123
      zone_name: "Untrust"
```

## Context

I try to automatise the initial build of a paloalto connected to a panorama. 

## Your Environment
- Panorama: PANOS 9.1.9
- Collection: paloaltonetworks.panos 2.6.0
- Python: 3.8.5
- Ansible: 2.10.10
- PAN-OS Python Library & version 
  - pan-os-python          1.2.0
  - pan-python             0.16.0

**Comment by gdmndr** [comment]
by forcing the vsys parameter to "vsys1" the module is working, the parameters is not initialised to this value as it's said in the documentation : 

vsys (type: str)
The vsys this object should be imported into. Objects that are imported include interfaces, virtual routers, virtual wires, and VLANs. Interfaces are typically imported into vsys1 if no vsys is specified.

```
---
- name: test csv file
  hosts: pan
  connection: local
  gather_facts: False
  tasks:
  - name: create subinterface for interconnexions
    paloaltonetworks.panos.panos_l3_subinterface :
      provider: '{{ provider }}'
      template: "test_Template"
      name: "ethernet1/1.123"
      enable_dhcp: yes
      tag: 123
      zone_name: "Untrust"
      vsys: "vsys1"
```
