### ISSUE TITLE
panos_loadcfg does not accept provider dict

### ISSUE THREAD

**Issue by Nothing4You** [PaloAltoNetworks/pan-os-ansible#245]
## Describe the bug

`panos_loadcfg` currently only accepts `ip_address`, `password` and `username` parameters directly instead of the `provider` parameter used in most other modules.
As far as I can tell this is just a regular XML API call and should therefore support the `provider` configuration just fine, which would enable the user to provide an API key to the module instead of passing username and password.

## Expected behavior

`provider` dict should be accepted like it is in most other modules, such as `panos_type_cmd`.

## Current behavior

```
fatal: [host]: FAILED! => {"changed": false, "msg": "missing required arguments: ip_address, password"}
```

## Possible solution

Implement support for the `provider` dict as alternative to `username` and `password`.

## Steps to reproduce

```yaml
- name: "load new config as candidate config"
  paloaltonetworks.panos.panos_loadcfg:
    provider: "{{ provider }}"
    file: "{{ pa_xml_staging_filename }}"
    commit: false
```

1. `ansible-playbook playbook.yml`

## Context

I was trying to authenticate using just an API key instead of having to pass username + password to the module.
This currently forces me from using just the API key for authentication.

## Your Environment

- Collection: 2.7.0
- Python: 3.9
- Ansible: 2.11.0
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pan-os-python 1.2.0
