### ISSUE TITLE
panos_address_object without Description is not idempotent

### ISSUE THREAD

**Issue by jvanderaa** [PaloAltoNetworks/pan-os-ansible#27]
## Describe the bug

When omitting the description parameter to the task, the description key is always presented as changing. The description parameter is listed as optional and should not attempt to make a change when there is nothing set.

## Expected behavior

I'd expect that if no description is provided and the rest of the rule is present that there would be no changes made.

## Current behavior

```
-<entry name="MyNet"><ip-netmask>192.0.2.0/24</ip-netmask></entry>
\ No newline at end of file
+<entry name="MyNet"><ip-netmask>192.0.2.0/24</ip-netmask><description /></entry>
\ No newline at end of file
```

## Possible solution

I need take a look at the code to see why description is still being sent if not defined.

## Steps to reproduce

1. Create an address object task with only `name`, `type`, and `value` defined
2. Continuously run a playbook with the task
3. It comes back with a change being made every time

## Context

Looking to have a fully idempotent configuration.

**Comment by mrichardson03** [comment]
Can you share details about your environment and the playbook you are using?  I can't reproduce.

**Comment by jvanderaa** [comment]
**Task**
```yaml
    - name: "TASK 110: PANORAMA >> CREATE ADDRESS OBJECTS"
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        commit: false
        name: "{{ item['name'] }}"
        device_group: "shared"
        value: "{{ item['value'] }}"
        address_type: "{{ item['type'] }}"
        description: "{{ item['description'] | default('') }}"
      register: create_address_objects
      tags:
        - "address_objects"
        - "addresses"
      loop: "{{ address_objects }}"
      loop_control:
        label: "{{ item['name'] }}"
```

**Group Vars**
```yaml
address_objects:
  - name: Test Object 1
    type: ip-netmask
    value: 192.0.2.0.1/30
  - name: Test Object 2
    type: ip-netmask
    value: 203.0.113.1/24
```

Working on getting a valid output. I'm having troubles accessing the remote environment at this time. Every time this is pushed I get a changed response, even though nothing is changed. The response when I do a `--diff` is that there is a description in the setup.
