### ISSUE TITLE
panos_security_rule is always changed due to uuid returned

### ISSUE THREAD

**Issue by pmalinen** [PaloAltoNetworks/pan-os-ansible#310]
## Describe the bug

When creating rules with panos_security_rule using the below template rules are always registered as changed since uuid is returned in before and compared to the after:

```
- name: permit dns to 1.1.1.1
      panos_security_rule:
        provider: "{{ panorama_provider }}"
        device_group: "{{ device_group }}"
        rule_name: 'DNS permit'
        description: 'DNS rule test'
        source_zone: ['trust']
        destination_zone: ['untrust']
        source_ip: ['any']
        source_user: ['any']
        destination_ip: ['1.1.1.1']
        category: ['any']
        application: ['dns']
        service: ['application-default']
        hip_profiles: ['any']
        action: 'allow'
        state: 'present'
        commit: false
```

## Expected behavior

Existing firewall rules that has not changed should not return a changed: true

## Current behavior

All rules are returned as changed

## Possible solution

Either add support for uuid or remove it when comparing the before/after

## Steps to reproduce

Run the above playbook:

```
"changed": true,
    "diff": {
        "after": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<entry name=\"ansible-test-dns-permit\">\n\t<from>\n\t\t<member>any</member>\n\t</from>\n\t<to>\n\t\t<member>internet</member>\n\t</to>\n\t<source>\n\t\t<member>any</member>\n\t</source>\n\t<source-user>\n\t\t<member>any</member>\n\t</source-user>\n\t<destination>\n\t\t<member>1.1.1.1</member>\n\t</destination>\n\t<application>\n\t\t<member>dns</member>\n\t</application>\n\t<service>\n\t\t<member>application-default</member>\n\t</service>\n\t<category>\n\t\t<member>any</member>\n\t</category>\n\t<action>allow</action>\n\t<log-start>no</log-start>\n\t<log-end>yes</log-end>\n\t<description>DNS rule test</description>\n\t<rule-type>universal</rule-type>\n\t<negate-source>no</negate-source>\n\t<negate-destination>no</negate-destination>\n\t<disabled>no</disabled>\n\t<option>\n\t\t<disable-server-response-inspection>no</disable-server-response-inspection>\n\t</option>\n\t<source-hip>\n\t\t<member>any</member>\n\t</source-hip>\n\t<destination-hip>\n\t\t<member>any</member>\n\t</destination-hip>\n</entry>\n",
        "before": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<entry name=\"ansible-test-dns-permit\" uuid=\"544ee9f1-759d-4194-bb08-ca1f02669ffa\">\n\t<from>\n\t\t<member>any</member>\n\t</from>\n\t<to>\n\t\t<member>internet</member>\n\t</to>\n\t<source>\n\t\t<member>any</member>\n\t</source>\n\t<source-user>\n\t\t<member>any</member>\n\t</source-user>\n\t<destination>\n\t\t<member>1.1.1.1</member>\n\t</destination>\n\t<application>\n\t\t<member>dns</member>\n\t</application>\n\t<service>\n\t\t<member>application-default</member>\n\t</service>\n\t<category>\n\t\t<member>any</member>\n\t</category>\n\t<action>allow</action>\n\t<log-start>no</log-start>\n\t<log-end>yes</log-end>\n\t<description>DNS rule test</description>\n\t<rule-type>universal</rule-type>\n\t<negate-source>no</negate-source>\n\t<negate-destination>no</negate-destination>\n\t<disabled>no</disabled>\n\t<option>\n\t\t<disable-server-response-inspection>no</disable-server-response-inspection>\n\t</option>\n\t<source-hip>\n\t\t<member>any</member>\n\t</source-hip>\n\t<destination-hip>\n\t\t<member>any</member>\n\t</destination-hip>\n</entry>\n"
    },
```
After adding uuid in the above playbook and in the module panos_security_rule:
```
    "changed": false,
    "diff": {
        "before": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<entry name=\"ansible-test-dns-permit\" uuid=\"544ee9f1-759d-4194-bb08-ca1f02669ffa\">\n\t<from>\n\t\t<member>any</member>\n\t</from>\n\t<to>\n\t\t<member>internet</member>\n\t</to>\n\t<source>\n\t\t<member>any</member>\n\t</source>\n\t<source-user>\n\t\t<member>any</member>\n\t</source-user>\n\t<destination>\n\t\t<member>1.1.1.1</member>\n\t</destination>\n\t<application>\n\t\t<member>dns</member>\n\t</application>\n\t<service>\n\t\t<member>application-default</member>\n\t</service>\n\t<category>\n\t\t<member>any</member>\n\t</category>\n\t<action>allow</action>\n\t<log-start>no</log-start>\n\t<log-end>yes</log-end>\n\t<description>DNS rule test</description>\n\t<rule-type>universal</rule-type>\n\t<negate-source>no</negate-source>\n\t<negate-destination>no</negate-destination>\n\t<disabled>no</disabled>\n\t<option>\n\t\t<disable-server-response-inspection>no</disable-server-response-inspection>\n\t</option>\n\t<source-hip>\n\t\t<member>any</member>\n\t</source-hip>\n\t<destination-hip>\n\t\t<member>any</member>\n\t</destination-hip>\n</entry>\n"
    },
```

## Your Environment

- Collection: 2.9.0
- Python: 3.8.9
- Ansible: 2.10.17
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):
- pandevice 0.14.0 pan-os-python 1.7.2
