### ISSUE TITLE
Creating L3 interfaces

### ISSUE THREAD

**Issue by patrisilva** [PaloAltoNetworks/pan-os-ansible#317]
## Describe the bug

While trying to create L3 interfaces, using:
    - name: ethernet1 as L3
      paloaltonetworks.panos.panos_interface:
        provider: '{{ provider }}'
        if_name: '{{ item }}'
        mode: "layer3"
        zone_name: "Untrust-L3"
        vr_name: "default"
      with_items:
            - ethernet1/1

## Expected behavior

interface not created

## Current behavior

Error: TypeError: ParamPath.parse_value_from_xml_last_tag() missing 1 required positional argument: 'attr'\n",

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Collection:
- Python:
- Ansible:
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):

**Comment by shinmog** [comment]
Using pan-os-python v1.7.3, I cannot reproduce this error.

You can uninstall pandevice if you have pan-os-python.  The collection will preferentially use pan-os-python if it's present.

My play:

```yaml
  - name: Create
    panos_interface:
      provider: '{{ aws_provider }}'
      if_name: '{{ item }}'
      mode: 'layer3'
      zone_name: 'public'
    with_items:
      - ethernet1/1
```
