### ISSUE TITLE
panos_snmp_profile not idempotent with multiple snmp servers

### ISSUE THREAD

**Issue by fhsctv** [PaloAltoNetworks/pan-os-ansible#319]
## Describe the bug

I'm trying to configure snmp on panos using ansible and the following minimal code:
```
- name: set fact for snmp config
  set_fact:
    fw_snmp_config:
      profile: 'inv-snmp-profile'
      version: 'v2c'
      state: 'present'
      servers:
        - name: 'server1'
          manager: 'aaa.bbb.ccc.ddd'
          community: 'public'
          state: 'present'

        - name: 'server2'
          manager: 'bbb.ccc.ddd.eee'
          community: 'public'
          state: 'present'

- name: configure snmp profile
  panos_snmp_profile:
    provider: '{{ _fw_api_key_provider }}'
    name: '{{ fw_snmp_config.profile }}'
    version: '{{ fw_snmp_config.version }}'
    state: "{{ fw_snmp_config.state | default('present') }}"

- name: configure snmp v2c servers in an snmp profile
  panos_snmp_v2c_server:
    provider: '{{ _fw_api_key_provider }}'
    snmp_profile: "{{ fw_snmp_config.profile }}"
    name: "{{ _snmp.name }}"
    manager: "{{ _snmp.manager }}"
    community: "{{ _snmp.community | default('public') }}"
    state: "{% if fw_snmp_config.state in ['present'] %}{{ _snmp.state | default('present') }}{% else %}'absent'{% endif %}"
  loop: "{{ fw_snmp_config.servers | sort(attribute='name') }}"
  loop_control:
    loop_var: _snmp
```

## Expected behavior

- the task "configure snmp profile" leaves multiple snmp servers untouched if they already exist

## Current behavior
- the task "configure snmp profile" always deletes all but the first snmp server configured by the "configure snmp v2c servers in an snmp profile" task

## Steps to reproduce

1. configure an snmp profile using panos_snmp_profile module
2. configure more than one snmp server (using panos_snmp_v2c_server module) for the profile configured in (1)
3. run playbook twice (second run should not change anything)

## Context

We have two different snmp servers accessing the palo alto snmp interface.
Both servers have to be allowed to access the snmp interface

- Collection: paloaltonetworks.panos
- Python: v3.6.8
- Ansible: v2.9.27
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pan-os-python 1.7.3
