### ISSUE TITLE
DHCP interface IP address must be empty error when creating L3 subinterface

### ISSUE THREAD

**Issue by jamesbtate** [PaloAltoNetworks/pan-os-ansible#335]
## Describe the bug

Panorama returns DHCP error when creating L3 subinterface with DHCP disabled and a static IP address.

## Expected behavior

Subinterface configuration should be accepted by Panorama.

## Current behavior

Error (I formatted the dict for easier reading):
```
TASK [Subinterface] **********************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "Failed create:  ethernet1/9.2501 -> dhcp-client constraints failed : DHCP interface IP address must be empty\n ethernet1/9.2501 -> dhcp-client is invalid"
}
```

## Possible solution

Configuration accepted when IP address parameter not specified (commented out `ip` in task).
Error seems related to this old bug (on the old repo?): https://github.com/PaloAltoNetworks/ansible-pan/issues/247

## Steps to reproduce

Task:
```
- name: Subinterface
    panos_l3_subinterface:
      provider: '{{ provider }}'
      name: ethernet1/9.2501
      tag: 2501
      enable_dhcp: false
      ip: ['10.20.30.9/28']
      create_default_route: False
      ipv6_enabled: False
      comment: my comment
      vr_name: '{{ vrouter }}'
      template: '{{ template }}'
      zone_name: '{{ zone }}'
      vsys: '{{ vsys }}'
```

Provider configured with ip_address, username and password. Other variables have suitable values and task works if `ip` parameter is commented out. However, in that case it appears in the GUI with type: DHCP (instead of static).

## Context

Just trying to configure subinterfaces automatically.

## Your Environment

- Collection: paloaltonetworks.panos 3.0.0
- Python: Python 3.6.8 (RHEL 7 `python3` package)
- Ansible: 2.10.9
- pan-os-python (1.7.3)
- pan-python (0.17.0)
- Panorama 9.1.13-h1
