### ISSUE TITLE
Error PanObject.add() missing 1 required positional argument: 'child'\n" on using BGP Peer Group Creation Task in Ansible

### ISSUE THREAD

**Issue by gwoodwa1** [PaloAltoNetworks/pan-os-ansible#339]
## Describe the bug

When running the BGP Peer Group Creation Task, it always fails with the following traceback message from Ansible:

`ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py\", line 478, in process\nTypeError: PanObject.add() missing 1 required positional argument: 'child'\n",`

I have done some debugging and narrowed it down to this line of code in panos.py line : 478 ` parent.add(obj)`

full path : `ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py`

Extract of the block of code from panos.py:
```     
        # Attach the object to the parent.

        if self.sdk_cls is None:
            raise Exception("sdk_cls must be specified")
        elif not isinstance(self.sdk_cls, tuple) or len(self.sdk_cls) != 2:
            raise Exception("helper.sdk_cls must be tuple of len()=2")
        obj = to_sdk_cls(*self.sdk_cls)(**spec)
        parent.add(obj)
```

Here is the full playbook  which just does the BGP Peer Group Creation Task. I have removed any optional parameters for debugging purposes
```
- hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

    interfaces:
      - if_name: 'ethernet1/1'
        mode: 'layer3'
        ip: ['192.168.55.20/24']
        enable_dhcp: false
      - if_name: 'ethernet1/2'
        mode: 'layer3'
        ip: ['192.168.45.20/24']
        enable_dhcp: false
      - if_name: 'ethernet1/3'
        mode: 'layer3'
        ip: ['192.168.35.20/24']
        enable_dhcp: false

  tasks:


    - name: Create BGP Peer Group
      paloaltonetworks.panos.panos_bgp_peer_group:
        provider: '{{ device }}'
        state: 'present'
        name: 'peer-group-4'
```

## Expected behavior

I think the obj variable should contain the correct output such that the parent class is not complaining about a missing child element

## Current behavior

Consistent Traceback message as above

![image](https://user-images.githubusercontent.com/63735312/188701182-ce980b9d-420b-49de-9d93-8f6517880b32.png)

## Possible solution

Having identified the line of code where it is failing, I wonder if the structure of the obj variable/object is incorrect and I would like to know what is expected and how I could examine that. I assumed it was a dictionary object of some sort with contents?
## Steps to reproduce

1. I am using a PanOS VM container created via containerlab
2. Built on PA-VM-KVM-10.1.6

## Context

I am testing provisioning of BGP for PanOS

## Your Environment

- Collection:
- Python: Python 3.10.4
- Ansible: ansible 2.10.8
- PAN-OS Python Library & version pan-os-python==1.4.0 pan-python==0.16.0 Ansible plugin : paloaltonetworks.panos 3.0.0
