### ISSUE TITLE
PANOS - Unable to remove multi objects from address group

### ISSUE THREAD

**Issue by xkoldxx** [PaloAltoNetworks/pan-os-ansible#342]
## Describe the bug

I followed the following guide:
https://live.paloaltonetworks.com/t5/automation-api-blog/ansible-using-facts-modules-to-do-updates/ba-p/275173 

it does remove the first item from my list but needs to be restarted to to remove any after that 

Code example

```
  tasks:
    # Convert CSV to Ansible Var
    - name: Covert CSV to Vars
      read_csv:
        path: address_group_remove_object.csv
      delegate_to: localhost
      register: object_vars
    # Query
    - name: Retrieve address group object
      paloaltonetworks.panos.panos_address_group:
        provider: '{{ provider }}'
        name: 'Group-Test'
        state: 'gathered'
        device_group: 'DG-Test'
      register: result

    # Create Object
    - name: Update Address Group(s)'
      paloaltonetworks.panos.panos_address_group:
        provider: "{{ provider }}"
        device_group: "{{ item.Device_Group }}"
        name: "{{ item.Name }}"
        description: "{{ item.Description }}"
        static_value: "{{ result.gathered.static_value | reject('in', item.Object) }}"
      loop_control:
        label: '{{ item.Name }}'
      loop: "{{ object_vars.list }}"
      when:
        - result.gathered.static_value
        - item.Object in result.gathered.static_value
```

## Expected behavior
i expected the task to iterate and change the item.Object then remove it from the gathered list

**Comment by shinmog** [comment]
You've got a looping issue that is outside the scope of the collection itself, as using a regular playbook, I am able to delete multiple entries at once with a single play, with a followup play being a no-op.

Here is my attempted repro:

```yaml
  - name: create obj1
    panos_address_object:
      provider: '{{ aws_provider }}'
      name: 'addy1'
      description: 'three is the magic number'
      address_type: 'ip-netmask'
      value: '10.2.3.1'

  - name: create obj2
    panos_address_object:
      provider: '{{ aws_provider }}'
      name: 'addy2'
      description: "can't we all just read together"
      address_type: 'ip-netmask'
      value: '10.2.3.2'

  - name: create obj3
    panos_address_object:
      provider: '{{ aws_provider }}'
      name: 'addy3'
      description: 'it can mean a couple different things'
      address_type: 'ip-netmask'
      value: '10.2.3.3'

  - name: create group
    panos_address_group:
      provider: '{{ aws_provider }}'
      name: 'wutang'
      description: 'my description'
      static_value: [
        'addy1',
        'addy2',
        'addy3',
      ]

  - name: modify
    panos_address_group:
      provider: '{{ aws_provider }}'
      name: 'wutang'
      description: 'my description'
      static_value: [
        'addy2',
      ]

  - name: modify (should be noop)
    panos_address_group:
      provider: '{{ aws_provider }}'
      name: 'wutang'
      description: 'my description'
      static_value: [
        'addy2',
      ]

  - name: delete address group
    panos_address_group:
      provider: '{{ aws_provider }}'
      name: 'wutang'
      state: 'absent'
```

Here is the result:

```bash
bash$ ansible-playbook -i hosts g2.yml 
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting 
with Ansible 2.12. Current version: 3.7.6 (default, Feb  3 2020, 14:26:19) [Clang 11.0.0 
(clang-1100.0.33.17)]. This feature will be removed from ansible-core in version 2.12. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [Network Playbook] ***********************************************************************

TASK [Grab auth creds] ************************************************************************
ok: [10.8.202.114]

TASK [create obj1] ****************************************************************************
ok: [10.8.202.114]

TASK [create obj2] ****************************************************************************
ok: [10.8.202.114]

TASK [create obj3] ****************************************************************************
ok: [10.8.202.114]

TASK [create group] ***************************************************************************
changed: [10.8.202.114]

TASK [modify] *********************************************************************************
changed: [10.8.202.114]

TASK [modify (should be noop)] ****************************************************************
ok: [10.8.202.114]

TASK [delete address group] *******************************************************************
changed: [10.8.202.114]

PLAY RECAP ************************************************************************************
10.8.202.114               : ok=11   changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

bash$ 
```
