### ISSUE TITLE
need request for module SNMP setup 

### ISSUE THREAD

**Issue by fortisfortunaadiuvat** [PaloAltoNetworks/pan-os-ansible#346]
I want to config the SNMP-setup on **Devices** > **Setup** > **Operations** > **miscellaneous** > **SNMP Setup**
but i think there’s  no module for it,
i hope you can create module for SNMP-setup 

Thank You

**Comment by jamesholland-uk** [comment]
Hi @fortisfortunaadiuvat,
Thanks for the enhancement request. In the meantime, you can use `panos_type_cmd` to achieve the same result. For example:
```
    - name: Define SNMP settings on firewall
      paloaltonetworks.panos.panos_type_cmd:
        provider: "{{ provider }}"
        cmd: "set"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system"
        element: "<snmp-setting><access-setting><version><v2c><snmp-community-string>{{ community_string }}</snmp-community-string></v2c></version></access-setting><snmp-system><location>{{ location }}</location><contact>{{ contact }}</contact><send-event-specific-traps>yes</send-event-specific-traps></snmp-system></snmp-setting>"

```
