### ISSUE TITLE
panos_aggregate_interface fails to create / update AE interfaces

### ISSUE THREAD

**Issue by CrimsonBinome24** [PaloAltoNetworks/pan-os-ansible#365]
## Describe the bug

panos_aggregate_interface fails to create / update AE interfaces

## Expected behavior

Should create / update AE interfaces

## Current behavior

Fails with following error:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: parse_value_from_xml_last_tag() missing 1 required positional argument: 'attr'
failed: [*redacted*] (item={'name': 'ae2', 'mode': 'layer3', 'zone_name': 'untrust'}) => {"ansible_loop_var": "item", "changed": false, "item": {"mode": "layer3", "name": "ae2", "zone_name": "untrust"}, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1671560860.0460176-8334-261111493265859/AnsiballZ_panos_aggregate_interface.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1671560860.0460176-8334-261111493265859/AnsiballZ_panos_aggregate_interface.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1671560860.0460176-8334-261111493265859/AnsiballZ_panos_aggregate_interface.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_panos_aggregate_interface_payload_kahxur5x/ansible_panos_aggregate_interface_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_aggregate_interface.py\", line 228, in <module>\n  File \"/tmp/ansible_panos_aggregate_interface_payload_kahxur5x/ansible_panos_aggregate_interface_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_aggregate_interface.py\", line 224, in main\n  File \"/tmp/ansible_panos_aggregate_interface_payload_kahxur5x/ansible_panos_aggregate_interface_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py\", line 484, in process\n  File \"/tmp/ansible_panos_aggregate_interface_payload_kahxur5x/ansible_panos_aggregate_interface_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py\", line 707, in apply_state\n  File \"/usr/local/lib/python3.6/dist-packages/panos/base.py\", line 3478, in set_vsys\n    True,\n  File \"/usr/local/lib/python3.6/dist-packages/panos/base.py\", line 1605, in _set_reference\n    obj.refresh_variable(reference_var)\n  File \"/usr/local/lib/python3.6/dist-packages/panos/base.py\", line 970, in refresh_variable\n    var_path.parse_value_from_xml_last_tag(obj, settings)\nTypeError: parse_value_from_xml_last_tag() missing 1 required positional argument: 'attr'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

## Possible solution

May require upgrade of host operating system / software. Unable to test at this time

## Steps to reproduce

Create and run a playbook with the following vars and task

Vars:
`AEInterfaces:
 - { name: "ae1", mode: "layer3", zone_name: "untrust"}
 - { name: "ae2", mode: "layer3", zone_name: "untrust"}
`

Playbook:
````yaml
    - name: Setup Internal  AE Group
      panos_aggregate_interface:
        if_name: "{{ item.name }}"
        provider: "{{ provider }}"
        mode: "{{ item.mode }}"
        state: present
        zone_name: "{{ item.zone_name }}"
        commit: "no"
      loop: "{{ AEInterfaces|flatten (levels=1) }}"
````
## Your Environment

- Collection: paloaltonetworks.panos 2.12.2
- Python: Python 3.6.9
- Ansible: ansible [core 2.11.9]

- PAN-OS Python Library & version
- pan-os-python          1.7.1
- pan-python             0.18.0

**Comment by jamesholland-uk** [comment]
Hi @CrimsonBinome24, I was unable to replicate this one with my current lab setup. I do have newer versions of Ansible/Python. You could try upgrading per your original issue notes.

```
---
- name: Configure things
  hosts: "firewall1"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    AEInterfaces:
      - { name: "ae1", mode: "layer3", zone_name: "untrust" }
      - { name: "ae2", mode: "layer3", zone_name: "untrust" }

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Setup Internal AE Group
      panos_aggregate_interface:
        if_name: "{{ item.name }}"
        provider: "{{ device }}"
        mode: "{{ item.mode }}"
        state: present
        zone_name: "{{ item.zone_name }}"
        commit: "no"
      loop: "{{ AEInterfaces|flatten (levels=1) }}"
```
```
$ ansible-playbook temp.yml

PLAY [Configure things] ********************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [firewall1]

TASK [Setup Internal AE Group] *************************************************************************************************************************************************************
changed: [firewall1] => (item={'name': 'ae1', 'mode': 'layer3', 'zone_name': 'untrust'})
changed: [firewall1] => (item={'name': 'ae2', 'mode': 'layer3', 'zone_name': 'untrust'})

PLAY RECAP *********************************************************************************************************************************************************************************
firewall1                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

paloaltonetworks.panos 2.12.2
ansible core 2.14.0
python 3.10.4
pan-os-python 1.7.3
pan-python 0.17.0
