### ISSUE TITLE
panos_commit_push for log collector group gives NoneType exception

### ISSUE THREAD

**Issue by ShreyasNBS** [PaloAltoNetworks/pan-os-ansible#369]
## Describe the bug

When I run the following code

```
- name: push log collector config to EW firewalls
  paloaltonetworks.panos.panos_commit_push:
    provider: '{{ provider }}'
    description: 'push log collector config to firewalls'
    style: 'log collector group'
    name: "LogCollectorGroup"

- name: wait for commits to finish
  paloaltonetworks.panos.panos_check:
    provider: '{{ rovider }}'
    initial_delay: 5
    interval: 5
    timeout: 100
```

I get the exception

```
TASK [push log collector config to firewalls] *******************************
--
  | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
  | fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/opt/app/.ansible/tmp/ansible-tmp-1672958494.5937903-242-47407665068504/AnsiballZ_panos_commit_push.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/opt/app/.ansible/tmp/ansible-tmp-1672958494.5937903-242-47407665068504/AnsiballZ_panos_commit_push.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/opt/app/.ansible/tmp/ansible-tmp-1672958494.5937903-242-47407665068504/AnsiballZ_panos_commit_push.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_commit_push', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_commit_push', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_commit_push_payload_xwl_us8v/ansible_paloaltonetworks.panos.panos_commit_push_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_commit_push.py\", line 206, in <module>\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_commit_push_payload_xwl_us8v/ansible_paloaltonetworks.panos.panos_commit_push_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_commit_push.py\", line 194, in main\nTypeError: 'NoneType' object is not subscriptable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

I have a device group and template stack configured via ansible and they work fine when I commit. The only "gotcha" could be that I do not have any managed firewalls added yet (but if the  behaviour was consistent, then commit to device group and template stack should also fail?)

I am using the latest panos ansible collection, and I am on panorama 10.2.2-h2.

**Comment by jamesholland-uk** [comment]
FYI: This is a pan-os-python issue, it is reproducible outside of Ansible. We will need to [progress a fix in that SDK](https://github.com/PaloAltoNetworks/pan-os-python/issues/487) to fix this issue.

**Comment by ShreyasNBS** [comment]
@jamesholland-uk Can we add the ignore_disconnect flag like we have on panos_op? We had a similar issue in the past when you set serial number (empty response).

```
- name: set panorama serial number if it does not match the current one
  no_log: true
  paloaltonetworks.panos.panos_op:
    provider: '{{ primary_provider }}'
    cmd: "<set><serial-number>{{ primary_panos_data['serial_number'] }}</serial-number></set>"
    cmd_is_xml: true
    ignore_disconnect: true
  when: "serial != primary_panos_data['serial_number']"
```
