### ISSUE TITLE
panos_security_rule does not permit External Dynamic Lists

### ISSUE THREAD

**Issue by darkhonor** [PaloAltoNetworks/pan-os-ansible#377]
## Describe the bug

When adding an external dynamic source address to a security rule, the rule fails as an invalid source.

## Expected behavior

When running the following task

```
- name: Create Default High-Risk Network Block
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ device }}'
    rule_name: 'High Risk Block'
    description: 'Default block for traffic coming from high-risk sources'
    source_zone: ['{{ internet_zone_name }}']
    source_ip:
      - "Palo Alto Networks - Tor exit IP addresses"
      - "Palo Alto Networks - Bulletproof IP addresses"
      - "Palo Alto Networks - High risk IP addresses"
      - "Palo Alto Networks - Known malicious IP addresses"
    destination_zone: '{{ internet_zone_name }}'
    destination_ip: 'any'
    application: 'any'
    service: 'any'
    log_start: false
    log_end: true
    location: 'top'
    action: 'deny'
    state: present
```

the system should create the specified rule.  The source ip's listed are valid an specified under "Objects -> External Dynamic Lists"

## Current behavior

When running the previous task, I receive the following error:

`
TASK [Create Default High-Risk Network Block] ********************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed create:  High Risk Block -> source 'Palo Alto Networks - Tor exit IP addresses' is not an allowed keyword\n High Risk Block -> source Palo Alto Networks - Tor exit IP addresses is an invalid ipv4/v6 address\n High Risk Block -> source Palo Alto Networks - Tor exit IP addresses invalid range start IP\n High Risk Block -> source 'Palo Alto Networks - Tor exit IP addresses' is not a valid reference\n High Risk Block -> source is invalid"}
`

## Possible solution

I'm not sure where this is being filtered from.  When specifying -vvvv, only the same info as expected is being passed.  

`
            "source_ip": [
                "Palo Alto Networks - Tor exit IP addresses",
                "Palo Alto Networks - Bulletproof IP addresses",
                "Palo Alto Networks - High risk IP addresses",
                "Palo Alto Networks - Known malicious IP addresses"
            ],
`

## Steps to reproduce

See the above task to reproduce.

## Screenshots

<img width="1127" alt="panos-external_dynamic_lists" src="https://user-images.githubusercontent.com/22874423/213905229-b2b3f8ac-7c60-4596-9a34-335cfd04b629.png">

## Context

This is part of my top-level security rules to block potentially dangerous sources.  These lists are provided by Palo Alto Networks for this very purpose and should be valid entries to any security policy.

## Your Environment

- Collection: 2.13.0
- Python: 3.10.6
- Ansible: 2.13.6
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pan-os-python 1.8.0; pan-python 0.17.0; pandevice 0.14.0
