### ISSUE TITLE
location and existing_rule options don't seem to work as intended.

### ISSUE THREAD

**Issue by richardjohnallsopp** [PaloAltoNetworks/pan-os-ansible#394]
## Describe the bug
I'm using the `location` and `existing_rule` options to set the location of new rules I deploy with ansible, however whatever values I set these options to the new rule installs at the end of the device group list.

## Expected behavior
I would expect that if I set an existing rule in the `existing_rule` option and set a location in the `location` option that the new rule(s) I push would be added relative to these settings, it instead ignores `top`, `bottom`, `after` and `before`, as well as the `existing_rule` and adds it at the end.

Variables:
```
test_policy:
  # GP to old prod pulse observability team
  - name: 'ANSIBLE policy deployment test'
    action: 'allow'
    device_group: 'World'
    rulebase: 'post-rulebase'
    location: 'before'
    existing_rule: 'Line in the sand rule' <----------- this exists in the panorama device group.
    application:
      - 'ssl'
    category:
      - 'any'
    # double quotes to catch grammar
    description: "test rule"
    destination_ip:
      - '10.40.0.0/16'
    destination_zone:
      - 'Trust-L3'
    group_profile:
      - 'Internal'
    log_setting: 'default'
    service:
      - 'any'
    source_devices:
      - 'any'
    source_ip:
      - 'any'
    source_user:
      - 'any'
    source_zone:
      - 'GlobalProtect'
    tag_name:
      - 'GlobalProtect'
    disabled: true
    commit: false
    state: 'present'
```
Play:
```
    - name: Add test post-rule to Panorama
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ provider }}'
        rule_name: '{{ item.name }}'
        rulebase: 'post-rulebase'
        description: '{{ item.description }}'
        source_zone: '{{ item.source_zone }}'
        destination_zone: '{{ item.destination_zone }}'
        source_ip: '{{ item.source_ip }}'
        source_user: '{{ item.source_user }}'
        destination_ip: '{{ item.destination_ip }}'
        category: '{{ item.category }}'
        application: '{{ item.application }}'
        service: '{{ item.service }}'
        hip_profiles: '{{ item.hip_profiles | default(omit) }}'
        action: '{{ item.action }}'
        device_group: '{{ item.device_group }}'
        disabled: '{{ item.disabled }}'
        commit: '{{ item.commit }}'
        state: '{{ item.state }}'
      with_items: '{{ test_policy }}'
```

## Current behavior
The rule is added successfully but regardless of the options set it's always the last rule in the device group. 

## Steps to reproduce
1. Using the same code as above you should be able to see the issue.

## Screenshots
![pan](https://user-images.githubusercontent.com/50882889/220659412-a3be233f-b10b-4973-b527-4b1d66b38de1.png)

## Context
This is blocking me deploying the automation I have written as some of the features need rules above existing ones.

## Your Environment
- Collection: 2.13.1
- Python: 3.9.11
- Ansible: 2.10.6
- PAN-OS Python Library: pan-os-python = latest, Panorama version = 10.2.3-h4
