### ISSUE TITLE
Import Keypair for PAN-OS 10.1+

### ISSUE THREAD

**Issue by jamesholland-uk** [PaloAltoNetworks/pan-os-ansible#399]
### Is your feature request related to a problem?
Importing a keypair from 10.1+ results in an error.
Task:
```
    - name: Import certificate
      paloaltonetworks.panos.panos_import:
        provider: '{{ device }}'
        category: 'keypair'
        certificate_name: 'local-ca'
        format: 'pkcs12'
        filename: './local-ca.p12'
        passphrase: 'somethingSecret'
```
Error:
`fatal: [vmseries-10dot1]: FAILED! => {"changed": false, "msg": "<response status=\"error\"><msg><line>Import of certificate and private-key local-ca failed. private key doesn't exist for csr</line></msg></response>"}`
### Describe the solution you'd like

It looks like the XML schema changed in 10.1, and `<keypair>` is now `<key>`. GUI debug from 10.0 and 10.1 compared:
![pan-os-10 1-onwards-xml-change-import-keypair](https://user-images.githubusercontent.com/6574404/222419927-9c154e9c-c393-4976-8a09-4f74f07f0c7a.png)

### Describe alternatives you've considered
N/A

### Additional context
N/A
