### ISSUE TITLE
not all modules are idempotent

### ISSUE THREAD

**Issue by fredericve** [PaloAltoNetworks/pan-os-ansible#4]
Not all of the modules are idempotent. E.g. when I enable bgp with ```panos_bgp```, then configure a peer group with ```panos_bgp_peer_group```, and then add a bunch of peers with ```panos_bgp_peer```, and then run the same playbook again, the ```panos_bgp``` task will remove the peers and peer_group, resulting in a ```changed``` state instead of ```ok```

## Expected behavior

Run a playbook with these tasks twice:
```
  - name: Configure BGP on a Virtual Router
    panos_bgp:
      provider: '{{ provider }}'
      state: present
      vr_name: default
      router_id: "{{ router_id }}"
      local_as: "{{ local_as }}"
      install_route: True
      reject_default_route: False
      commit: false

  - name: Configure BGP Peer Group
    panos_bgp_peer_group:
      provider: '{{ provider }}'
      state: present
      name: "{{ peer_group_name }}"
      vr_name: default
      commit: False

  - name: Configure BGP Peer
    panos_bgp_peer:
      provider: '{{ provider }}'
      state: present
      name: "{{ peer_name }}"
      enable: true
      peer_as: "{{ peer_as }}"
      local_interface_ip: "{{ peer_local_if_ip }}"
      local_interface: "{{ peer_local_if }}
      peer_address_ip: "{{ peer_addr_ip }}"
      peer_group: "{{ peer_group_name }}"
      vr_name: default
      commit: False
```

The second run each task should display ```ok```

## Current behavior

When run a second time, all tasks display ```changed```

## Possible solution

I believe the source of the problem is in ```module_utils/network/panos/panos.py``` ```apply_state``` function. In there the generated object only includes child types that exist in the new version of the object instead of leaving the existing children untouched.

## Your Environment

- Version used:
- Ubuntu 18.04, with pandevice 0.14.0
