### ISSUE TITLE
paloaltonetworks.panos.panos_commit_push not pushing to devices in device group

### ISSUE THREAD

**Issue by richardjohnallsopp** [PaloAltoNetworks/pan-os-ansible#400]
## Describe the bug

When using the `paloaltonetworks.panos.panos_commit_push` module the committed config in Panorama is not pushed to the devices in the specified device group. 

## Expected behaviour

I expected after using the `paloaltonetworks.panos.panos_commit_panorama` module to push changes to Panorama device groups that I would be able to use `paloaltonetworks.panos.panos_commit_push` module to push these changes to the devices in the specified device group.

## Current behavior

The `paloaltonetworks.panos.panos_commit_panorama` seems to work and I see the changes committed to Panorama for the specified device group, but after the `paloaltonetworks.panos.panos_commit_push` task completes successfully Panorama tells me that a push is needed as there is outstanding changes that were not pushed to devices. We have to manually push these changes. 

## Steps to reproduce

1. Using the latest collection version you should be able to push a commit to a Panorama device group and then use the push module to push the changes to the devices.

## Screenshots

![image](https://user-images.githubusercontent.com/50882889/222419726-645e0699-1f0f-432b-af57-c0ac5610352d.png)
![image](https://user-images.githubusercontent.com/50882889/222419886-16931b89-aaca-4359-9787-b2e08b517d46.png)

## Context

I've written a pipeline for automating the creation of objects, services and policies so we can convert this workflow into a Jenkins pipeline and IaC. It all works fine aside from the commit push meaning we cannot use the pipeline in production.

```
    - name: Create object(s) in Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        address_type: '{{ item.type }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_object }}'
      when: world_object is defined and item.state == 'present'

    - name: Create global service(s) in Panorama
      paloaltonetworks.panos.panos_service_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        destination_port: '{{ item.destination_port }}'
        source_port: '{{ item.source_port | default(omit) }}'
        protocol: '{{ item.protocol }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_service }}'
      when: world_service is defined and item.state == 'present'

    - name: Manage post-rule(s) in Panorama
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ provider }}'
        rule_name: '{{ item.name }}'
        rulebase: 'post-rulebase'
        location: '{{ item.location }}'
        existing_rule: '{{ item.existing_rule }}'
        description: '{{ item.description }}'
        source_zone: '{{ item.source_zone }}'
        destination_zone: '{{ item.destination_zone }}'
        source_ip: '{{ item.source_ip }}'
        source_user: '{{ item.source_user }}'
        destination_ip: '{{ item.destination_ip }}'
        category: '{{ item.category }}'
        application: '{{ item.application }}'
        service: '{{ item.service }}'
        hip_profiles: '{{ item.hip_profiles | default(omit) }}'
        action: '{{ item.action }}'
        device_group: '{{ item.device_group }}'
        disabled: '{{ item.disabled }}'
        state: '{{ item.state }}'
        # commit: '{{ item.commit }}'
      with_items: '{{ world_policy }}'

    - name: Remove object(s) in Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        address_type: '{{ item.type }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_object }}'
      when: world_object is defined and item.state == 'absent'

    - name: Remove global service(s) in Panorama
      paloaltonetworks.panos.panos_service_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        destination_port: '{{ item.destination_port }}'
        source_port: '{{ item.source_port | default(omit) }}'
        protocol: '{{ item.protocol }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_service }}'
      when: world_service is defined and item.state == 'absent'

    # spacific panorama commit
    - name: Commit candidate config on Panorama
      paloaltonetworks.panos.panos_commit_panorama:
        provider: '{{ provider }}'
        device_groups:
          - 'World'
        admins:
          - 'admin'
        description: 'Commit - {{ commit_description }}'
        sync: true
      tags:
        - "push"

    - name: Commit and push config via Panorama
      paloaltonetworks.panos.panos_commit_push:
        provider: '{{ provider }}'
        style: 'device group'
        name: 'World'
        #admins:
        #  - 'admin'
        sync: true
        description: 'Push - {{ commit_description }}'
      tags:
        - "push"
```

## Your Environment

- Collection: 2.13.2
- Python: 3.9.11
- Ansible: 2.10.6
- PAN-OS Python Library & version pan-os-python==1.8.1, pandevice==0.14.0
- Panorama: 10.2.3-h4

**Comment by jamesholland-uk** [comment]
Hi @richardjohnallsopp, does the config definitely not push to the managed devices (NGFWs) with your playbook?
With Panorama 10.2.3-h4 I can replicate the GUI issue, where all managed devices are in sync but the GUI still incorrectly shows the icon and tooltip stating "pending push changes". This is a PAN-OS issue which needs to be reported through your usual support channel. However, I used the tasks in the example playbook above, and whilst that GUI issue is present, the playbook did actually push and commit the changes to the managed devices successfully, so I was unable to replicate an issue with the Ansible modules. Please let us know, thanks

**Comment by richardjohnallsopp** [comment]
Hey @jamesholland-uk, I can confirm that the changes are not pushed to the firewalls, I'd be interested in seeing if your task in Panorama for the push shows devices it pushed to. Mine as above is empty and completes much faster than a manual push to that device group from Panorama.

Panorama also shows that all devices in the device group are out of sync after the Ansible push completes which currently blocks any future changes by other users.

**Comment by jamesholland-uk** [comment]
Hi @richardjohnallsopp, yes, mine did have the managed device listed and took a "usual" duration to complete the push:
![Screenshot 2023-03-06 at 10 22 25](https://user-images.githubusercontent.com/6574404/223083804-f68181ee-ffb7-409e-b020-88c090fb044d.png)

And the managed device is in sync after:
![Screenshot 2023-03-06 at 10 33 26](https://user-images.githubusercontent.com/6574404/223085849-b301a6ff-f7c6-4e80-8def-43fcf710d1a7.png)


If the push to the managed devices(s) does not really happen, you can understand it not being in sync. The question therefore is, why is the push is not initiating properly?

For reference, here's the simplified version of the playbook I am using:
```
---
- name: Palo Alto Playbook
  hosts: '{{ target | default("host_homelabrama") }}'
  connection: local

  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"
    commit_description: "Change ref 123"

  tasks:
    - name: Create object(s) in Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        name: 'aaaa-ertert'
        value: '1.1.1.1'
        device_group: 'poc-dg'

    # spacific panorama commit
    - name: Commit candidate config on Panorama
      paloaltonetworks.panos.panos_commit_panorama:
        provider: '{{ provider }}'
        device_groups:
          - 'poc-dg'
        admins:
          - 'ansible-admin'
        description: 'Commit - {{ commit_description }}'
        sync: true
      tags:
        - "push"

    - name: Commit and push config via Panorama
      paloaltonetworks.panos.panos_commit_push:
        provider: '{{ provider }}'
        style: 'device group'
        name: 'poc-dg'
        # admins:
        #   - 'admin'
        sync: true
        description: 'Push - {{ commit_description }}'
      tags:
        - "push"
```

**Comment by richardjohnallsopp** [comment]
Yeah that does not happen with mine. Our plays are virtually the same as well, but my commit task is blank. 

Are we running the same versions of the collections and Ansible etc...

**Comment by jamesholland-uk** [comment]
I'm on ansible-core 2.14.3, PAN-OS collection 2.13.2, python 3.10.9, pan-os-python 1.8.1

**Comment by jamesholland-uk** [comment]
There's nothing in the `device_groups` or `admins` parameters that would lead to an empty commit or push is there? No unintended values for those parameters? Mine are all hard-coded, your config tasks use a variable on the device_groups for example?

**Comment by richardjohnallsopp** [comment]
Not that I can see, I used the same variables to commit the code to Panorama and that looks solid, the push is just style: device group and name: World. I can try with latter versions and see if that makes a difference. Richard AllsoppEpic GamesSenior Infrastructure Engineer Mobile +447590263111On 6 Mar 2023, at 13:10, James Holland ***@***.***> wrote:﻿
There's nothing in the device_groups or admins parameters that would lead to an empty commit or push is there? No unintended values for those parameters? Mine are all hard-coded, your config tasks use a variable on the device_groups for example?

**Comment by scottgravitt** [comment]
It looks like the config gets trucated: 
```
  <destination-h <<< here 
2023-03-03 15:24:49.112 +0000 Warning:  pan_hash_init(pan_hash.c:113): nbuckets 16536 is not power of 2!
2023-03-03 15:24:49.190 +0000 String is <entry name="ANSIBLE policy deployment test" uuid="67875cd0-9a6b-4785-9d3e-5c9ad12656d7">

and 

  <destination-hi <<< here
2023-03-03 15:24:49.212 +0000 pan_cfg_replaydb_get_uncommited_changes_mongo: Retrieved 100 uncommited replaydb entries from mongo db
2023-03-03 15:24:49.299 +0000 Error:  pan_cfg_get_session_by_cookie(pan_cfg_mgr.c:14810): session with cookie static doesn't exist
2023-03-03 15:24:49.299 +0000 Error:  pan_cfg_get_session_by_cookie(pan_cfg_mgr.c:14810): session with cookie static doesn't exist
2023-03-03 15:24:52.289 +0000 Error:  pan_job_refresh_job_cache(pan_job_mgr.c:13228): job 1320358 not found
```
[02485185_confd.txt](https://github.com/PaloAltoNetworks/pan-os-ansible/files/10911323/02485185_confd.txt)

We are also seeing configd crash, the root partition filling up and the HA Panorama pair failing over: 
```
/opt/panlogs/cores/:
total 0

/var/cores/:
total 8.0K
drwxr-xr-x 2 root root 4.0K Feb 28 06:20 crashinfo
drwxr-xr-x 2 root root 4.0K Mar 3 21:49 crashjobs <<<

/var/cores/crashinfo:
total 512K
rw-rw-rw 1 root root 507K Feb 28 06:20 reportd-20230228062014-10.2.3-h4.info

/var/cores/crashjobs:
total 0
rw-rr- 1 root root 0 Feb 23 19:28 configd-20230223192848.tmp
rw-rr- 1 root root 0 Mar 3 21:49 configd-20230303214911.tmp <<<
```
Panoramas failed over:
```
2023/03/03 21:50:30 2023/03/03 21:50:30 critical ha system- 0 000702890609 High root partition usage; going to state Non-Functional
2023/03/03 21:50:30 2023/03/03 21:50:30 critical ha state-c 0 000702890609 Moved from state Active to state Non-Functional
```
We have asked for verification on this defect being impacted in 10.2 code. At present the Panoramas are running 10.2.3-h4 but the firewalls are on 10.1.6-h6: PAN-160053 - Fixed an issue in Panorama where a process (configd) stopped responding due to a race condition in the mongodbprocess.

Palo Case: 02485185S2

**Comment by jamesholland-uk** [comment]
Thanks @scottgravitt, is this the same deployment as @richardjohnallsopp or are you separate? We can leave this issue open for no if you want, or close it (knowing that you can reopen it if the TAC ticket does not fix the root cause and you want to circle back to the Ansible module)?

**Comment by scottgravitt** [comment]
This is the same environment @jamesholland-uk. I am waiting for a meeting w/ TAC to 'rebuild the mongodb from root.' This should happen either later today or tomorrow, so let's leave it open and I'll update on the outcome.

**Comment by scottgravitt** [comment]
@jamesholland-uk we are still working with PA TAC on a root cause here. It definitely seems to be an issue on our Panorama, so from my perspective we can close this one out and we'll provide an update on the root cause/workaround/fix as the information becomes available.

**Comment by jamesholland-uk** [comment]
Thank you for the update @scottgravitt, much appreciated. I hope the issue gets resolved ASAP. If you do need to revisit the behaviour of this module, you can always reopen this Issue or create a new one.

**Comment by cdot65** [comment]
I have been able to reproduce this situation in my lab environment,

```bash
❯ pip freeze | grep ansible
ansible==8.0.0
ansible-core==2.15.0

❯ pip freeze | grep pan-
pan-os-python==1.11.0
pan-python==0.17.0

❯ ansible-galaxy collection list | grep palo
paloaltonetworks.panos 2.16.0 
```

Panorama version `10.2.4`

```yaml
---
- hosts: panorama
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: "Creating a test address object"
      paloaltonetworks.panos.panos_address_object:
        provider:
          ip_address: "{{ ansible_host }}"
          api_key: "{{ panorama_api_key }}"
        name: "Gaming-PC"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC"
        device_group: "headquarters"
        state: "absent"
      register: result

    - name: commit candidate configs on panorama
      paloaltonetworks.panos.panos_commit_panorama:
        provider:
          ip_address: "{{ ansible_host }}"
          api_key: "{{ panorama_api_key }}"

    - name: push device group configs
      paloaltonetworks.panos.panos_commit_push:
        provider:
          ip_address: "{{ ansible_host }}"
          api_key: "{{ panorama_api_key }}"
        style: "device group"
        name: "headquarters"
        description: "This is a test."
```

result screenshot

<img width="817" alt="image" src="https://github.com/PaloAltoNetworks/pan-os-ansible/assets/76797306/714941a9-0554-447c-8c57-d092baa4722e">

Object is never pushed to remote firewalls in Device Group.
