### ISSUE TITLE
Configure Inbound Decryption for PAN-OS 10.2+ enhancement

### ISSUE THREAD

**Issue by jamesholland-uk** [PaloAltoNetworks/pan-os-ansible#401]
### Is your feature request related to a problem?
Configuring a decryption rule for `inbound inspection` from 10.2+ results in an error.
Task:
```
- name: test_panos_decryption_rule - Create inbound inspection rule
  paloaltonetworks.panos.panos_decryption_rule:
    provider: '{{ device }}'
    name: 'Test'
    source_zones: ['inside']
    source_addresses: ['any']
    destination_zones: ['outside']
    destination_addresses: ['1.1.1.1']
    services: ['service-https']
    action: 'decrypt'
    decryption_type: 'ssl-inbound-inspection'
    ssl_certificate: 'local-ca'
    decryption_profile: 'default'
```
Error:
`fatal: [panos-10dot2]: FAILED! => {"changed": false, "msg": "Failed create:  Test -> type -> ssl-inbound-inspection unexpected here\n Test -> type -> ssl-inbound-inspection  is unexpected \n Test -> type is invalid"}`

The XML schema changes in 10.2 to accommodate a new feature allowing multiple certificates to be used. The parameter for a certificate changed from a single string (the cert name) to a list of strings (a list of cert names).

### Describe the solution you'd like
Accommodate all current supported version of PAN-OS for creating decryption rules for inbound inspection.

### Describe alternatives you've considered
N/A

### Additional context
N/A
