### ISSUE TITLE
panos_aggregate_interface - LACP options are missing

### ISSUE THREAD

**Issue by antoinekh** [PaloAltoNetworks/pan-os-ansible#421]
## Documentation link

https://ansible-pan.readthedocs.io/en/latest/modules/panos_aggregate_interface_module.html

## Describe the problem

This 3 options are missing on the documentation:
```
  lacp_passive_pre_negotiation:
        description:
            - Enable LACP passive pre-negotiation
        type: bool
    lacp_rate:
        description:
            - Set LACP transmission rate
        type: str
        choices: ['fast', 'slow']
    lacp_mode:
        description:
            - Set LACP mode
        type: str
        choices: ['active', 'passive']
```

## Suggested fix

Add these options to the documentation

But they are well defined here:
https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_aggregate_interface_module.html
