### ISSUE TITLE
panos_config_element not editing content and AV update schedules

### ISSUE THREAD

**Issue by ShreyasNBS** [PaloAltoNetworks/pan-os-ansible#424]
Hi,

We have panorama HA, and are trying to move away from "sync-to-peer" to each panorama having it's own content and AV update schedules. However, after running the ansible playbook, we see the output as "changed", and the changes committed to panorama, but the UI still shows no changes to schedule? Not sure what we are missing here.

OLD CODE with sync-to-peer enabled

```
- name: add anti-virus update schedule
  paloaltonetworks.panos.panos_config_element:
    provider: '{{ primary_provider }}'
    xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/anti-virus/recurring"
    element: "<daily><at>{{ ANTIVIRUS_INSTALL_SCHEDULE_DAILY_TIME }}</at><action>download-and-install</action></daily><threshold>1</threshold><sync-to-peer>yes</sync-to-peer>"
- name: add application and threats update schedule
  paloaltonetworks.panos.panos_config_element:
    provider: '{{ primary_provider }}'
    xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/threats/recurring"
    element: "<weekly><at>{{ CONTENT_INSTALL_SCHEDULE_WEEKLY_TIME }}</at><day-of-week>saturday</day-of-week><action>download-and-install</action><disable-new-content>no</disable-new-content></weekly><threshold>{{ CONTENT_UPDATE_SCHEDULE_HOURLY_THRESHOLD }}</threshold><new-app-threshold>{{ CONTENT_UPDATE_SCHEDULE_HOURLY_THRESHOLD }}</new-app-threshold><sync-to-peer>yes</sync-to-peer>"
```

NEW CODE with each pano having it's own content update schedule:

PRIMARY/ACTIVE Pano

```
- name: "{{ instance_type }} - add anti-virus update schedule"
  paloaltonetworks.panos.panos_config_element:
    provider: '{{ primary_provider }}'
    edit: true
    xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/anti-virus/recurring"
    element: "<recurring><daily><at>{{ PRIMARY_PANO_ANTIVIRUS_INSTALL_SCHEDULE_DAILY_TIME }}</at><action>download-and-install</action></daily><threshold>1</threshold></recurring>"

- name: "{{ instance_type }} - add application and threats update schedule"
  paloaltonetworks.panos.panos_config_element:
    provider: '{{ primary_provider }}'
    edit: true
    xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/threats/recurring"
    element: "<recurring><weekly><at>{{ PRIMARY_PANO_CONTENT_INSTALL_SCHEDULE_WEEKLY_TIME }}</at><day-of-week>saturday</day-of-week><action>download-and-install</action><disable-new-content>no</disable-new-content></weekly><threshold>{{ CONTENT_UPDATE_SCHEDULE_HOURLY_THRESHOLD }}</threshold><new-app-threshold>{{ CONTENT_UPDATE_SCHEDULE_HOURLY_THRESHOLD }}</new-app-threshold></recurring>"
```

SECONDARY/PASSIVE Pano

```
- name: "{{ instance_type }} - add anti-virus update schedule"
  paloaltonetworks.panos.panos_config_element:
    provider: '{{ secondary_provider }}'
    edit: true
    xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/anti-virus/recurring"
    element: "<recurring><daily><at>{{ SECONDARY_PANO_ANTIVIRUS_INSTALL_SCHEDULE_DAILY_TIME }}</at><action>download-and-install</action></daily><threshold>1</threshold></recurring>"

- name: "{{ instance_type }} - add application and threats update schedule"
  paloaltonetworks.panos.panos_config_element:
    provider: '{{ secondary_provider }}'
    edit: true
    xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/threats/recurring"
    element: "<recurring><weekly><at>{{ SECONDARY_PANO_CONTENT_INSTALL_SCHEDULE_WEEKLY_TIME }}</at><day-of-week>saturday</day-of-week><action>download-and-install</action><disable-new-content>no</disable-new-content></weekly><threshold>{{ CONTENT_UPDATE_SCHEDULE_HOURLY_THRESHOLD }}</threshold><new-app-threshold>{{ CONTENT_UPDATE_SCHEDULE_HOURLY_THRESHOLD }}</new-app-threshold></recurring>"
```

The output shows success:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/56643631/233381363-1870c07b-e4ee-45e6-a5cc-1a72c210cc4f.png">

However the settings do not apply in **PASSIVE** Panorama:

Primary/Active is correct

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/56643631/233381588-59266c64-fc3f-4b85-a066-8c7927a65a50.png">

Secondary/Passive is not set. Do we need to make Secondary as Active first before applying this?

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/56643631/233381751-700f3198-5c01-48fe-8c42-f56da99731a3.png">
