### ISSUE TITLE
Getting XML Parse errors when using panos_config_element module

### ISSUE THREAD

**Issue by alexortize** [PaloAltoNetworks/pan-os-ansible#438]
I believe the panos_config_element doesn't always work like it is supposed to. For example I get xml ParseError exception when trying to update my device groups. Example playbook is below. The same xpath and element were tested using ansible.builitin.uri module and works just fine.
```
---

- name: Set master device for device groups
  hosts: panorama
  gather_facts: false
  connection: local


  tasks:
    - name: Run show devicegroups command
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: "show devicegroups"
      register: result

    - name: Parse JSON
      ansible.builtin.set_fact:
        result: "{{ result.stdout | from_json }}"

    - name: Get devicegroups entries
      ansible.builtin.set_fact:
        devicegroups: "{{ result.response.result.devicegroups.entry }}"

    - name: Set master device for device groups
      paloaltonetworks.panos.panos_config_element:
        provider: "{{  provider }}"
        xpath: "/config/devices/entry/device-group/entry[@name='{{ device_group }}']"
        element: |
          <user-group-source>
            <master-device>
              <device>{{ serials[index|int] }}</device>
              <sync-group>yes</sync-group>
            </master-device>
          </user-group-source>
      vars:
        device_group: "{{ item.get('@name') }}"
        entry: "{{ item.devices.entry | default([]) }}"
        entry_type: "{{ entry | type_debug }}"
        serials: "{% if entry_type == 'dict' %}{{ (entry.get('@name'),) | list }}{% else %}{{ entry | map(attribute='@name') | list }}{% endif %}"
        hostnames: "{% if entry_type == 'dict' %}{{ (entry.hostname,) | list }}{% else %}{{ entry | map(attribute='hostname') | list }}{% endif %}"
        index: "{{ lookup('ansible.utils.index_of', hostnames, 'regex', 'pri') | default(0) }}"
      loop: "{{ devicegroups }}"
      when: 
        - entry
```
