### ISSUE TITLE
panos_bgp_peer_group export-nexthop 'resolve' is not an allowed keyword error for type: ibgp

### ISSUE THREAD

**Issue by robobeaver6** [PaloAltoNetworks/pan-os-ansible#441]
## Describe the bug

The task:
```
- name: Create BGP Peer Group
  panos_bgp_peer_group:
    provider: "{{ provider }}"
    name: "Group_Name"
    type: "ibgp"
    enable: true
```
gives the error:
```
fatal: [lolnoobfw1]: FAILED! => changed=false 
  msg: |-
    Failed apply:  Group_Name-> type -> ibgp -> export-nexthop 'resolve' is not an allowed keyword
     Group_Name -> type -> ibgp -> export-nexthop is invalid
```
By setting either the `type: "ebgp"` or the  `export_nexthop: "use-self"` will work.  

## Expected behavior

the cli has no `export-nexthop` setting when ibgp is used, the module shouldn't set it to "resolve", it shouldn't be present

## Current behavior

It throws the error unless `use-self` is set which is somewhat meaningless as it is not an option on the CLI

## Possible solution

don't set or require the variable `export-nexthop`  when `type: ibgp` is set 

## Steps to reproduce

run the task above

## Context

I am templating the config of our remote devices using ansible because Panorama templates don't provide variables to all the parameters required.

## Your Environment

- Collection: paloaltonetworks.panos
- Python: 3.9
- Ansible: 2.14.4
