### ISSUE TITLE
error with gathered_filter parameter in module

### ISSUE THREAD

**Issue by jonchen8** [PaloAltoNetworks/pan-os-ansible#473]
## Describe the bug

Getting a module failure using an option from ["Operators - No Value"](https://paloaltonetworks.github.io/pan-os-ansible/gatheredfilter.html#operators-no-value) in gathered_filter parameter of a module.
The module in question is the nat_rule2 module.

## Expected behavior

when setting `state: 'gathered'` and `gathered_filter: 'destination_addresses is-not-none'` (this also applies to the operator `is-none`)
I should be able to query all my nat policies that does not have its `destination_addresses` attribute as none.
This also applies to the other attributes of a nat policy

## Current behavior

I am currently getting failures stating `Improperly formatted logic string`

## Possible solution

Not for certain on this, but it appears it's not attempting the [try](https://github.com/PaloAltoNetworks/pan-os-ansible/blob/c75fea759d65a965d45b4e17e5d2f298eb851155/plugins/module_utils/panos.py#L1200) operation as the [exception](https://github.com/PaloAltoNetworks/pan-os-ansible/blob/c75fea759d65a965d45b4e17e5d2f298eb851155/plugins/module_utils/panos.py#L1202) is using the error message as it is appearing `err_msg = "Improperly formatted logic string"`

## Steps to reproduce

1. ensure there are nat policies on the palo alto panorma with `none` in any of the address fields (and have a nat policy with the address field populated)

2. set up the following tasks in a playbook
panos_provider is a dictionary that contains the panorama host, username, and password
palo_device_group is a string to points to a particular device group on the panorama

``` yml
    - name: 'Query panos nat policies'
      paloaltonetworks.panos.panos_nat_rule2:
        provider: "{{ panos_provider }}"
        device_group: "{{ palo_device_group }}"
        state: 'gathered'
        gathered_filter: 'destination_addresses is-not-none'
      register: _register_output

    - name: 'debug register'
      debug:
        msg: "{{ _register_output }}"
```
4. run the playbook

5. the first task would fail stating `The error was: Exception: Improperly formatted logic string`

## Screenshots

using the is-none operator
![image](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/110173621/bc6dc379-4a4c-435b-aa61-05f2f7f8998f)

using the is-not-none operator
![image](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/110173621/e2f2dd46-223c-4b19-a4ac-0bcd36bd372f)

## Context

this is preventing us to validate our policies by filtering the ones that do not apply for our validation

## Your Environment

- Collection: paloaltonetworks.panos 2.17.2
- Python: 3.8
- Ansible: 2.9.27
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pan-os-python 1.11.0, pandevice 0.14.0
