### ISSUE TITLE
Playbook hangs using panos_commit_firewall

### ISSUE THREAD

**Issue by nishthaGupta** [PaloAltoNetworks/pan-os-ansible#496]
## Describe the bug

Hello,

I have a use case wherein I need to load a standard day 1 configuration on the firewall device. The new config is supposed to delete the existing users & reset the admin password to default.
I am using panos_loadcfg & panos_commit_firewall modules for the same. I want to keep retrying the commit until the result is success since a failure is expected for the first or second time.

My usage is as follows:name: Commit the config changes
      - name: Load the configuration 
      ```
paloaltonetworks.panos.panos_loadcfg:
        ip_address: '{{ ansible_host }}'
        username: "user"
        password: "password"
        file: '{{ inventory_hostname }}.xml'

          paloaltonetworks.panos.panos_commit_firewall:
            provider: '{{ provider }}'
          register: rs
          until: rs is success
          retries: 10
```

What I am observing is that the playbook execution `hangs` after the commit gets successful. When I forcefully kill the process, I can see that the new config file was loaded successfully. I want to understand why the playbook execution hangs & how can I overcome this problem?

## Expected behavior

The above code snippet should work & playbook should gracefully stop execution upon a successful commit.

## Current behavior

The playbook execution hangs.

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Collection:
- Python:
- Ansible:
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):
