### ISSUE TITLE
DHCP interface IP address must be empty error when creating L3 subinterface-paloaltonetworks.panos 2.13.3 

### ISSUE THREAD

**Issue by rlison47** [PaloAltoNetworks/pan-os-ansible#497]
## Describe the bug

There's a DHCP Error in configure L3 subinterface a ' dhcp-client constraints failed : DHCP interface IP address must be empty\n ae2.869 -> dhcp-client is invalid"} after setting enabled DHCP to false and a static IP
## Expected behavior

An L3 subinterface will be created with a static IP below is my ansible script

- name: 'ae2.869'
        tag: '869'
        template: 'DIF_GEN_7080'
        gathered_filter: '*' 
        enable_dhcp: false
        vsys: 'DIF_GEN_PRD_BASTION'
        vr_name: 'BSTN_PRD_1'
        zone_name: 'BTSTN_IN_1'
        ip: ["10.164.241.6/29"]
        management_profile: 'INT_MGMT_PING'

## Current behavior

Instead of creating l3 subinterface with a static ip a dhcp error is prompted ' dhcp-client constraints failed : DHCP interface IP address must be empty\n ae2.869 -> dhcp-client is invalid"}

## Context

Need help on the fix as we need this ansible automation for our Panorama FW automation Project in our company

## Your Environment

Collection             Version
---------------------- -------
ansible [core 2.14.4]
ansible.netcommon      5.1.0  
ansible.posix          1.5.2  
ansible.utils          2.9.0  
ansible.windows        1.13.0 
python version = 3.10.6
paloaltonetworks.panos 2.13.3

**Comment by rlison47** [comment]
Hello, any help would be appreciated. Has anyone here experienced the issue regarding the panos_l3_subinterface_module?

**Comment by jamesholland-uk** [comment]
Hi @rlison47, I was able to use your code sample successfully. Here is my code which creates the dependencies, then creates the L3 subinterface:

```
---
- name: Palo Alto Networks Playbook
  hosts: '{{ target | default("host_gcprama") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: Create template
      paloaltonetworks.panos.panos_config_element:
        provider: "{{ device }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/template"
        element: "<entry name='DIF_GEN_7080'/>"

    - name: Create zone
      paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'BTSTN_IN_1'
        mode: 'layer3'
        vsys: "DIF_GEN_PRD_BASTION"
        template: "DIF_GEN_7080"

    - name: Create virtual router
      paloaltonetworks.panos.panos_virtual_router:
        provider: "{{ device }}"
        name: "BSTN_PRD_1"
        vsys: "DIF_GEN_PRD_BASTION"
        template: "DIF_GEN_7080"

    - name: Create aggregate interface
      paloaltonetworks.panos.panos_aggregate_interface:
        provider: "{{ device }}"
        template: "DIF_GEN_7080"
        vsys: "DIF_GEN_PRD_BASTION"
        if_name: ae2
        zone_name: BTSTN_IN_1

    - name: Crate interface_mgmt_profile
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ device }}'
        name: 'INT_MGMT_PING'
        ping: true
        template: "DIF_GEN_7080"

    - name: Test
      paloaltonetworks.panos.panos_l3_subinterface:
        provider: '{{ device }}'
        name: 'ae2.869'
        tag: '869'
        template: 'DIF_GEN_7080'
        gathered_filter: '*'
        enable_dhcp: false
        vsys: 'DIF_GEN_PRD_BASTION'
        vr_name: 'BSTN_PRD_1'
        zone_name: 'BTSTN_IN_1'
        ip: ["10.164.241.6/29"]
        management_profile: 'INT_MGMT_PING'
```

Note that the template, zone, virtual router, aggregate interface, interface management profile and L3 subinterface did not exist before executing this playbook.

![Screenshot 2023-09-26 at 11 34 21](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/14e76310-813f-4381-ae42-3565c9c89768)

![Screenshot 2023-09-26 at 11 31 55](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/4f76430e-4324-42d4-bf6f-c0b4d93bdc88)

I am using:
paloaltonetworks.panos 2.17.6
pan-os-python 1.11.0
pan-python 0.17.0
Panorama 10.2.4

Note that the `gathered_filter: '*'` line is superfluous and can be removed, because `gathered_filter` is only evaluated if state is set to gathered.
