### ISSUE TITLE
Don't seem to be able to use panos modules inside roles

### ISSUE THREAD

**Issue by dpisano** [PaloAltoNetworks/pan-os-ansible#5]
## Describe the bug
I don't seem to be able to use any of the modules when I use the in side a role.

## Expected behavior
To be able to use any module in the collections in a role.

## Current behavior
I have the following playbook that calls a role that I made.
```
---
- name: Config PA
  gather_facts: no
  connection: local
  hosts: all
  
  collections:
    - paloaltonetworks.panos

  roles:
    - pa-role
```
The pa-role has the following play in it:
```
  - name: Add IPv4 default route
    panos_static_route:
      provider: '{{ provider }}'
      name: 'default'
      destination: '0.0.0.0/0'
      nexthop: "{{ defult_route.ipv4 }}"
``` 

When I run this playbook I get the following error:
```
ERROR! couldn't resolve module/action 'panos_static_route'. This often indicates a misspelling, missing collection, or incorrect module path.
```
If I copy that play into a standalone playbook it work.
```
---
- name: Config PA
  gather_facts: no
  connection: local
  hosts: all
  
  collections:
    - paloaltonetworks.panos
  
  tasks:
  - name: Add IPv4 default route
    panos_static_route:
      provider: '{{ provider }}'
      name: 'default'
      destination: '0.0.0.0/0'
      nexthop: "{{ defult_route.ipv4 }}"
```

## Steps to reproduce

The snippets above are pulled from the code that I'm using. They should work to be able to reproduce it.
