### ISSUE TITLE
Module for upgrade assurance health checks

### ISSUE THREAD

**Issue by adambaumeister** [PaloAltoNetworks/pan-os-ansible#529]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

We should be able to run the health checks in the same way we can run readiness checks with an Ansible Task.

```yaml
- name: Run all management plane checks using NOT notation
  panos_health_checks:
    provider: '{{ device }}'
```

We use health checks to push out automated ways of looking for advisories that may affect PAN-OS firewalls, such as the recent certificate expiration issues.
