### ISSUE TITLE
Add LLDP configuration management

### ISSUE THREAD

**Issue by Nothing4You** [PaloAltoNetworks/pan-os-ansible#534]
### Is your feature request related to a problem?

Currently, to configure LLDP system settings and LLDP profiles, you have to figure out the relevant XML snippets and set them with `panos_config_element`.

### Describe the solution you'd like

LLDP system settings and LLDP profiles should be natively configurable via Ansible modules.

### Describe alternatives you've considered

```yml
- name: Enable LLDP
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ provider }}"

    edit: true
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/lldp
    element: |-
      <lldp>
        <enable>yes</enable>
      </lldp>

  diff: true


- name: Create LLDP profile default
  paloaltonetworks.panos.panos_config_element:
    provider: "{{ provider }}"

    edit: false
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/profiles/lldp-profile
    element: |-
      <entry name="default">
        <mode>transmit-receive</mode>
        <option-tlvs>
          <management-address>
            <enabled>no</enabled>
          </management-address>
          <port-description>yes</port-description>
          <system-name>yes</system-name>
          <system-description>yes</system-description>
        </option-tlvs>
      </entry>

  diff: true
```

### Additional context

I believe this requires adjustments in [pan-os-python](https://github.com/PaloAltoNetworks/pan-os-python) to make this possible.

It was also previously partially mentioned in #409, though it seems to me that it makes more sense in a dedicated issue for this.
