### ISSUE TITLE
Cannot enable nat rule

### ISSUE THREAD

**Issue by raqs31** [PaloAltoNetworks/pan-os-ansible#588]
## Describe the bug

panos_nat_rule2 cannot reenable disabled rule with state merged for version >2.21.0

## Expected behavior

Disabled rule should be enabled after play

## Current behavior

Ansible report no change and no desired changes affected on device

## Possible solution

Working correctly on tested versions:
- 2.20.0
- 2.19.x

## Steps to reproduce

1. Disable sample rule and commit changes
2. Run task for sample rule
    ```yaml
      tasks:
        - name: configure nat rule disabled
          paloaltonetworks.panos.panos_nat_rule2:
            provider: "{{ provider }}"
            name: "{{ rule_name }}"
            state: merged
            disabled: false
    ```

## Your Environment

- Collection: paloaltonetworks.panos 2.21.2
- Python: 3.9.18
- Ansible: ansible [core 2.17.5]
- PAN-OS Python Library & version pan-os-python 1.8.0, pan-python 0.17.0, xmltodict 0.12.0
