### ISSUE TITLE
Strange timestamp using panos_op

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/pan-os-ansible#59]
Im having a strange issue when trying to use ansible to get a list of all the unused rules from panorama, the timestamps get weird in the output (i need to have the timestamps, since i will later delete the unused rules that was create 3+ month ago.

```

  tasks:
    - name: Get hit count for rule
      paloaltonetworks.panos.panos_op:
#        provider: '{{ device }}'
        ip_address: 1.1.1.1
        api_key: '13371337'
        cmd:  |
          <show><rule-hit-count><device-group><entry name='fw01'><pre-rulebase><entry name='security'><rules><all/></rules></entry></pre-rulebase></entry></device-group></rule-hit-count></show>
        cmd_is_xml: True
      changed_when: false
      register: initial
    - debug:
        msg: "{{ (initial.stdout )}}"

```
When doing the command from the cli it looks like this.

```
020-08-06 09:37:56
<response status="success"><result>Rule Name                                                         Rule Usage          Rule Create Timestamp         Rule Modify Timestamp        
---------------------------------------------------------------------------------------------------------------------------------------------------------
133711510-32724-01                                             Partially Used      Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
test-userid                                                       Partially Used      Mon Oct  7 16:48:14 2019      Tue Jan 14 15:53:38 2020     
133711522-32724-02                                             Unused              Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711540-32724-08                                             Unused              Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711528-32724-03                                             Used                Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711542-32724-09                                             Unused              Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711534-32724-04                                             Used                Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711544-32724-10                                             Unused              Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711535-32724-05                                             Unused              Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711547-32724-11                                             Used                Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711536-32724-06                                             Used                Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711549-32724-12                                             Unused              Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711537-32724-07                                             Used                Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711551-32724-13                                             Used                Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
133711552-32724-14                                             Unused              Mon Oct  7 16:48:14 2019      Mon Oct  7 16:48:14 2019     
20190819                                                          Used                Mon Oct  7 16:48:14 2019      Tue Mar 31 14:32:54 2020     
```

However the output from ansible looks like this:
```

ication-timestamp>1570697945</rule-modification-timestamp></entry><entry name="20200127094600"><rule-state>Used</rule-state><all-connected>yes</all-connected><rule-creation-timestamp>1580114892</rule-creation-timestamp><rule-modification-timestamp>1580123975</rule-modification-timestamp></entry><entry name="20200107130000"><rule-state>Partial</rule-state><all-connected>yes</all-connected><rule-creation-timestamp>1578398026</rule-creation-timestamp><rule-modification-timestamp>1578406587</rule-modification-timestamp></entry><entry name="20190829151302"><rule-state>Used</rule-state><all-connected>yes</all-connected><rule-creation-timestamp>1570459694</rule-creation-timestamp><rule-modification-timestamp>1575033480</rule-modification-timestamp></entry><entry name="Any-any"><rule-state>Used</rule-state><all-connected>yes</all-connected><rule-creation-timestamp>1570459694</rule-creation-timestamp><rule-modification-timestamp>1570459694</rule-modification-timestamp></entry><entry
    name="global-deny"><rule-state>Used</rule-state><all-connected>yes</all-connected><rule-creation-timestamp>1570459694</rule-creation-timestamp><rule-modification-timestamp>1570459694</rule-modification-timestamp></entry></rules></entry></rule-base></entry></device-group></rule-hit-count></result></response>

TASK [debug] ********************************************************************************************************************************************

  msg:
    response:
      '@status': success
      result:
        rule-hit-count:
          device-group:
            entry:
              '@name': fw01
              rule-base:
                entry:
                  '@name': security
                  rules:
                    entry:
                    - '@name': 133711510-32724-01
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Partial
                    - '@name': test-userid
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1579013618'
                      rule-state: Partial
                    - '@name': 133711522-32724-02
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Unused
                    - '@name': 133711540-32724-08
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Unused
                    - '@name': 133711528-32724-03
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Used
                    - '@name': 133711542-32724-09
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Unused
                    - '@name': 133711534-32724-04
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Used
                    - '@name': 133711544-32724-10
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Unused
                    - '@name': 133711535-32724-05
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Unused
                    - '@name': 133711547-32724-11
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Used
                    - '@name': 133711536-32724-06
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Used
                    - '@name': 133711549-32724-12
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Unused
                    - '@name': 133711537-32724-07
                      all-connected: 'yes'
                      rule-creation-timestamp: '1570459694'
                      rule-modification-timestamp: '1570459694'
                      rule-state: Used

```
