### ISSUE TITLE
panos_interface (and friends): cannot set IPv6 addresses

### ISSUE THREAD

**Issue by slrz** [PaloAltoNetworks/pan-os-ansible#6]
While the interface-related modules allow enabling IPv6 on an interface it doesn't seem to be possible to actually configure any addresses.

## Expected behavior

There should be **some** way to add IPv6 addresses to an interface.

## Current behavior

As far as I can tell, pan-os-ansible currently doesn't allow for IPv6 addressing configuration at all.

## Possible interface sketch:

```yaml
panos_vlan_interface:
  provider: "{{ provider }}"
  name: vlan.42
  zone_name: twilight_zone
  vr_name: default
  ipv6_enabled: yes
  ip:
    - '198.51.100.42/24'
  ipv6:
    - address: '2001:db8::42/64'
      advertise_enabled: yes
```

## Context

Trying to figure out how to drive a pair of PA-5200s.  If there's a more suitable way for setting up IPv6 addressing I'd happily try something else.
