### ISSUE TITLE
panos_interface - Unable to add variable IP on data interface in Panorama template

### ISSUE THREAD

**Issue by mhca99** [PaloAltoNetworks/pan-os-ansible#609]
## Describe the bug

I am adding an interface in Panorama template with panos_interface module where I use the IP address as variable ip "$transit_float_ip" instead of real ip , however its throwing error saying IP is invalid. 

## Expected behavior

As per module notes, the panos_interface module can be used to update the panorama template if template field is used, therefore it should be able accept the template variable "$transit_float_ip" and should not do IP validation check.  The reason is that we should be able to use the same template for multiple firewalls , therefore we provide interface IP as variable IP instead of dedicated static IP which will result in creating separate template for each firewall.  

## Current behavior

Module is throwing error with invalid IP. 

## Possible solution

Implement the logic so that if module is being used for template , it should accept IP field starting with "$xxx".

## Steps to reproduce

1. create ansible playbook with following code and run it 
```  
    - name: create interfaces in Panorama template
      paloaltonetworks.panos.panos_interface:
        provider: '{{ provider }}'
        template: 'global'
        if_name: "ethernet1/1"
        mode: "layer3"
        ip: "[ '$transit_float_ip' ]"
        enable_dhcp: false
```
2. it will produce the following error:
```
PLAY [Palo Alto test] ****************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [testhost]

TASK [create interfaces in Panorama template] ****************************************************************************************************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Failed create:  ethernet1/1 -> layer3 -> ip -> [ '$transit_float_ip' ] '[ '$transit_float_ip' ]' is invalid"}
```
## Your Environment

- Collection:  paloaltonetworks.panos   2.21.4
- Python: 3.12.3
- Ansible: 2.16.3
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):
  pan-os-python       1.12.1
  pan-python          0.17.0
  pandevice           0.14.0
