### ISSUE TITLE
panos_commit_panorama commits all pending changes regardless of user specified in admins list.

### ISSUE THREAD

**Issue by SMrunal17** [PaloAltoNetworks/pan-os-ansible#628]
Ansible Playbook snippet: 
--------------------------------------
collections:
  - paloaltonetworks.panos

vars:
  panorama_provider:
    ip_address: {{ panorama_fqdn }}
    username: {{ username }}
    password: {{ password }}
tasks:
  - name: Commit Config
    panos_commit_panorama:
  	provider: {% raw %}"{{ panorama_provider }}"{% endraw %}
  	sync: true
  	admins: ["{{ username }}"]		
--------------------------------------

Expectation: 
Should only commit changes made by admins specified in the list ({{ username }} in this case).

Current behaviour: 
Commits all pending changes made by all users. 
When I perform the same steps manually using the web portal, it works as expected.  I have observed this behavior only when using the Ansible playbook.

Panorama software version: 11.1.6
paloaltonetworks.panos version: 2.13.1

**Comment by adambaumeister** [comment]
@SMrunal17 can you please use the latest version of the Ansible collection (3.1.1) which should include a bumped `pan-os-python` dependency when testing this functionality.

On panos software 11.2.6 and collection version 3.1.1 I cannot reproduce this issue either on Panorama or NGFW instance.

**Task**
```yaml
    - name: Commit configuration to firewall
      #paloaltonetworks.panos.panos_commit_firewall:
      paloaltonetworks.panos.panos_commit_panorama:
        provider:
          ip_address: "{{ ip_address }}"
          username: "{{ username }}"
          password: "{{ password }}"
        sync: true
        admins:
          - adam
      register: commit_result
```

**Example of commit partial job in panorama**
<img width="601" height="148" alt="Image" src="https://github.com/user-attachments/assets/7b2a6d82-9fb2-484a-9d6b-5695f224d3c2" />

**Comment by SMrunal17** [comment]
Hi team, 

I tested the latest version (3.1.1) of the paloaltonetworks.panos Ansible collection, but unfortunately, the issue persists.

Additional context: 
===============================
This behavior arises when using the device_groups parameter within the panos_security_rule module to add security rules in Panorama, followed by a commit using panos_commit_panorama.
- If I omit the device_groups parameter, the panos_commit_panorama module commits only the changes made by the user specified in the admins parameter — which is the expected behavior.
- However, we cannot omit the device_groups parameter because we need to apply rules to a specific device group.

Code:
==============================
- name: "Palo Alto: Add Rules"
  hosts: {{ name }}
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    panorama_provider:
      ip_address: {{ panorama_fqdn }}
      username: {{ username }}
      password: {{ password }}
    rule_states: {}

  tasks:
    {% for service_name, service_attrs in services.items() %}
    - name: Create Service {{ service_name }}
      panos_service_object:
        provider: {% raw %}"{{ panorama_provider }}"{% endraw %}
        name: '{{ service_name }}'
        destination_port: '{{ service_attrs.port }}'
        protocol: '{{ service_attrs.proto }}'
        state: present
        commit: false
    {% endfor %}

    {% for rule_id, rule in rules.items() %}
    - name: Block and Rescue each rule
      block:
        - name: Add Rule {{ rule_id }}
          panos_security_rule:
            provider: {% raw %}"{{ panorama_provider }}"{% endraw %}
            device_group: "{{ device_groups[0].name }}"
            rulebase: "post-rulebase"
            rule_name:  "{{ rule.name }}"
            description:  "{{ rule.description }}"
            source_zone: ["{{ rule.src_zone }}"]
            source_ip:
              {% for net in rule.src_ip %}
              - "{{ net }}"
              {% endfor %}
            source_user: ["{{ rule.src_user }}"]
            destination_zone: ["{{ rule.dst_zone }}"]
            destination_ip:
              {% for net in rule.dst_ip %}
              - "{{ net }}"
              {% endfor %}
            application: ["{{ rule.application }}"]
            service: ["{{ rule.service }}"]
            log_setting: "{{ rule.log_setting }}"
            {% if rule.group_profile is defined %}
            group_profile: "{{ rule.group_profile }}"
            {% endif %}
            hip_profiles: ["any"]
            action: "{{ rule.action }}"
            location: "top"
            state: present
            commit: false

        - name: Mark {{ rule_id }} as successful
          set_fact:
            rule_states: {% raw %}"{{ rule_states | combine ({ '{% endraw %}{{ rule_id }}{% raw %}' : True }) }}"{% endraw %}
            cacheable: yes

      rescue:
        - name: Mark {{ rule_id }} as failed
          set_fact:
            rule_states: {% raw %}"{{ rule_states | combine ({ '{% endraw %}{{ rule_id }}{% raw %}' : False }) }}"{% endraw %}
            cacheable: yes
    {% endfor %}

    - name: Commit Config to Panorama
      panos_commit_panorama:
        provider: {% raw %}"{{ panorama_provider }}"{% endraw %}
        sync: true
        admins: ["{{ username }}"]

    - name: Push Config
      panos_commit_push:
        provider: {% raw %}"{{ panorama_provider }}"{% endraw %}
        style: "device group"
        sync: true
        name: "{{ device_groups[0].name }}"
        admins: ["{{ username }}"]
===========================================

In the above code snippet, I observed the following:
- When invoking commit, **it commits all configuration changes, including those made and left uncommitted by other users, not just the ones associated with the username specified in the admins parameter** — and across all device groups.
- When invoking push, it correctly pushes configuration changes specific to the mentioned device group and the user defined in the admins parameter.

**Comment by bearlaska** [comment]
Even when creating both objects using ansible module, they are merged into a single change and ownership is set to last account used.

```yaml
    - name: manage address objects
      paloaltonetworks.panos.panos_address_object:
        name: address-object-maxmuster
        address_type: ip-netmask
        value: "10.71.1.34"
        provider: "{{ provider }}"
        device_group: "pa-lab"
        state: present
      tags: panorama.address_objects

    - name: manage address objects
      paloaltonetworks.panos.panos_address_object:
        name: address-object-mustermax
        address_type: ip-netmask
        value: "10.71.1.12"
        provider: "{{ provider2 }}"
        device_group: "pa-lab"
        state: present
      tags: panorama.address_objects
```



<img width="862" height="522" alt="Image" src="https://github.com/user-attachments/assets/7823e843-6ee2-454c-8435-0c69f5bbdb22" />

---

Doing the same steps for both objects using web-ui with different accounts results in 2 separate changes which can be commited independently. I would expect the same from ansible module.

<img width="1283" height="567" alt="Image" src="https://github.com/user-attachments/assets/84425dc4-37eb-4811-9f8a-1b429d713f65" />

**Comment by adambaumeister** [comment]
Hiya, I think I have found what the issue is.

Basically pan-os-python, when it applies the ansible configuration, is doing so one XML parent element "back" and using the 'edit' operation to do so. When it does this, it is essentially overriding the candidate configuration at that xpath and 'taking ownership' of it. This normally doesn't matter but in your case you have correctly identified that it's breaking the 'commit only changes by...' logic because of that.

This is reproducible, and in fact it doesn't matter if the changes are outside of the same parent element, for example, if you use two seperate providers to create two seperate *types* of object it works correctly.

tasks:

```yaml
  tasks:
    - name: Create ADDRESS OBJECT iwth FIRST Provider
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        device_group: "Lab"
        name: "TEST-1-DELETEME"
        value: "1.1.1.1/32"
        address_type: "ip-netmask"
        state: present

    - name: Create TAG OBJECT with SECOND Provider
      paloaltonetworks.panos.panos_tag_object:
        provider: "{{ provider2 }}"
        device_group: "Lab"
        name: "TEST-2-DELETEME"
        state: present
```

<img width="1320" height="626" alt="Image" src="https://github.com/user-attachments/assets/6aa53bda-36ac-4972-af5c-68a88e46f664" />

We will need to think how best to solve this as it may require a considerable amount of code changes to rectify.
