### ISSUE TITLE
Support batch mode in panos_software

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/pan-os-ansible#63]
It would be nice if it would be possible to use a image already uploaded to the device (uploaded with panorama).
Some of our remote sites has a quite crappy and slow internet connection. We usualy prepear the upload some day before the upgrade.

**Comment by mrichardson03** [comment]
Current `panos_software` module would have to be extended to support batch mode (download updates from Panorama instead of update server).

**Comment by ishuguru** [comment]
From what i can see in the api the firewall are referenced by serialnr when using batch mode. So it will be quite messy to write a module for this i guess.

**Comment by mrichardson03** [comment]
This can be accomplished using `panos_op`.

**Comment by appandya84** [comment]
@mrichardson03 I am currently facing same issue where I want to upload image to firewall from Panorama then install that image locally to firewall. You mentioned same can be accomplished using panos_op. please can you advise on that? also if there has been any feature released for this issue? Thanks in advance.

**Comment by jamesholland-uk** [comment]
Hi @appandya84, we have [a guide](https://pan.dev/ansible/docs/panos/guides/offline-content-software-upgrade/) that goes through a very similar process with `panos_op`, it should be extendable to include the Panorama part. I hope that helps

**Comment by appandya84** [comment]
@jamesholland-uk I was wondering if PAN-OS module will work with Panorama cli? From Panorama cli, there are commands we can run to upload software to firewall then install and reboot firewall directly from Panorama cli. So running this Automation guide directly on panorama may be another fix if it supports panorama. Has this been tested? Thanks

**Comment by jamesholland-uk** [comment]
Hi @appandya84, I don't think I have personally tested that exact use case. However, if you look at the code in the guide, you will see how to use the `panos_op` module to perform the equivalent of `request` CLI commands:
```
 - name: Start content installation
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "<request><content><upgrade><install><skip-content-validity-check>yes</skip-content-validity-check><file>{{ content_file }}</file></install></upgrade></content></request>"
        cmd_is_xml: true
      register: contentinstall
```

You should be able to reuse that approach to achieve your goal if the CLI commands you're referring to are able to be executed using an XML API call like that example I gave here. Hope that helps
