### ISSUE TITLE
Layer3 Subinterface creation throws an error but creates configuration

### ISSUE THREAD

**Issue by salsop** [PaloAltoNetworks/pan-os-ansible#64]
## Describe the bug

When I execute this playbook extract on Panorama v9.1.2:

``` 
# Add a subinterface
    - name: add subinterface to template
      panos_l3_subinterface:
          provider: '{{ provider }}'
          template: 'Test_Template'
          name: 'ae1.1234'
          zone_name: 'Trust'
          tag: 1234 
          ip: '10.10.10.1/24'
          vr_name: 'Router1'
          enable_dhcp: false
```

I get the following error back, but the creation succeeds:

```fatal: [panorama]: FAILED! => {"changed": false, "msg": "Failed setref:  layer3 'ae1.1234' is not a valid reference"}```

## Expected behavior

Should not throw error.

## Current behavior

Thows the error above

## Possible solution

I think this is because the command is trying to set 'layer3' on subinterface but not required on GUI.

## Steps to reproduce

As above.

## Screenshots

None
