### ISSUE TITLE
panos_security_rule reports error, but achieves it's goal

### ISSUE THREAD

**Issue by jakunow** [PaloAltoNetworks/pan-os-ansible#92]
## Describe the bug

When creating new security rule with panos_security_rule and when location is specified (parameters **location** and **existing_rule** are used) then task reports as failed with **"msg": "; "** but it achieves it's goal and successfully creates rule in correct location.
When running same task without location specified (not **location** and **exisiting_rule**) then task is reported as ok

## Expected behavior

Ansible playbook's task should report it as OK.

## Current behavior

Ansible playbook's task is being reported as FAILED (but planned changes are implemented as expected).

## Possible solution

Use `  ignore_errors: yes`, so that playbook continues with next tasks.

## Steps to reproduce

```
  - name: Create Security Policy
    panos_security_rule:
      rule_name: 'security rule'
      tag_name: ['tag1']
      rule_type: 'interzone'
      source_zone: ['DMZ', 'TRUST']
      source_ip: ['source-{{ item.name }}','source-{{ item.name2 }}']
      destination_zone: ['DMZ', 'TRUST']
      destination_ip: ['source-{{ item.name }}','source-{{ item.name2 }}']
      service: ['any']
      action: 'allow'
      location: 'before'
      existing_rule: 'intrazone-custom'
      state: 'present'
      provider: '{{ provider }}'
      commit: 'False'
    loop: '{{ rule }}'
```

## Your Environment

Part of configuration (i.e. address objects are pushed to Firewalls from Panorama)

- Version used: PaloAltoNetworks.paloaltonetworks, v2.4.1
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Python 3.6.9
- Operating System and version (desktop or mobile):  Ubuntu 18.04.4 LTS
- Link to your project: N/A
